"""
D2C Sales Dashboard v4 — memory-efficient
=========================================
Built for 1-5M+ sales rows on low-RAM hosting. DuckDB reads the sales Parquet/CSV
directly from disk (streaming, low memory) and joins to the small master SKU sheet
inside the database. No giant pandas frame is held in RAM.

Sources:
  SALES : Parquet/CSV in Google Drive (DRIVE_FILE_ID) or local sample.
  MASTER: live Google Sheet (MASTER_SHEET_ID + MASTER_SHEET_TAB), keyed by sku_code (small).
Join: sales.sku (text) <-> master.sku_code (text)
"""
import streamlit as st
import traceback

try:
    import os, io, tempfile
    import duckdb
    import pandas as pd
    import plotly.express as px
    import plotly.graph_objects as go
    from pathlib import Path
except Exception:
    st.title("Startup error"); st.error("Import failed:"); st.code(traceback.format_exc()); st.stop()

HERE = Path(__file__).parent
SALES_LOCAL = HERE / "sales.parquet"
MASTER_LOCAL = HERE / "master.csv"

LOGO_B64 = "iVBORw0KGgoAAAANSUhEUgAAA8IAAACgCAYAAADHP9VhAABkx0lEQVR42u2dd7gkZZX/P9X3Tg4MaWCAGYYcJQuIKKAoRtYEa8CwillXf4rroq6KCQVzWPOaVlREwZwjKIIkkZxzmAFmhgkMc7urfn+c826fKaq7q/p2qOp7vs9Tz43dXfWG857wPedETB3UUj/HqZ/HgU2BLYEFwEK9tgK2A+brVQMWAYl5bQKMAfcCq4H7gQeAB4G7gDv15xXAMmBNh/tLUu/vcDgcDofD4XA4HI4eIZoCzxdlGL0AmwPbAzvo1/2A3YG9gNl9up+7gcuA6/S6CbgeuA2YaDM/bhQ7HA6Hw+FwOBwOhxvCtIv8piOqEbATsFQN38OAvZFI79YZ79FoMUZ5xytp8f1YxufciESM7wD+DPwFiSw/0CJiHPuydTgcDofD4XA4HA43hCM1MmNjKI4BOwJPAPYFjkZozjOB6WxMka6roRmZr/1AYu4xSd0HSFR4JXAtcKkaxZcDV2cY07FHih0Oh8PhcDgcDodj6hnCwXC1EdxdgScCTwIOAJZkPGcwIiNzDQOJMY6jjIgxahT/FokW/wmJFmMi306ddjgcDofD4XA4HI4pYAinc2dnAU8GjgSORSLBrajKZX7uTvd5CfAb4Czgooz/dYPY4XA4HA6Hw+FwOBjtys/bAy8G/ojQm0OEtY5EiWPzu6pegbptn+9u4Gzg6Wyc4xxljJHD4XA4HA6Hw+FwOCpqAI8ZY+9w4APAFcAGYyBuUAM4GdGrnnreNcC5wBuB3dg4jzjyZeNwOBwOh8PhcDgcVJICPW5+3gv4MHBPhoEYj7ABnL4aqQhxAlwFnIRUwm5VpdrhcDgcDofD4XA4HBXJX94W+DjSYihJVV+eSgZwFm06PQZXAG8D5k6hftEOh8PhcDgcDofDwajkAW8OvAn45xSO/hbNJQ4/XwQ8m42jwp4/7HA4HA6Hw+FwOByUrxUSSBXoY5H816mS/9vLPOJgEK8HzgQea8Z53Jeaw+FwOBwOh8PhcFCKKHAwgvcBvoIUgrI5sW7kdh8dvgf4ILCVGW+nSzscDofD4XA4HA5HCajQrwBuShl0bthOvrBW+P58JNLuVGmHw+FwOBwOh8PhYDhU6BCVXAx8GXhYDbYJN4L7FiFeh1SX3sSjww6Hw+FwOBwOh8PBQKPAoTXSU4FLcBr0oPKHw/c/AfbOoKY7HA6Hw+FwOBwOh4P+tEWag0QmVxsD2KPAg4kOh+9vAV5u5sQjww6Hw+FwOBwOh8NBf/KBtwLOMEZZXIE+va2uqucOrwdOZWOqtKMaaQX2clRnrny+HA6Hw+FwuO44BVsj7YMUbSp7FDgumH8bV7yQ1neBTd0YrkxefbvK645yybyic+lwOByOqXFGjJnz288EB31MR83C2FRfdxGDU94T4CnAZ4Cd1Hgs6wQk5p6XAVcCd+r9jgOLkKj2YqTnMcYoHqvYGggG8TjwF+DV+rw1fR5HefZqQrMX9CxgHpJasNbMlf0/x3DlamL6os/VPbUGeEjny+fK4XA4pqZDO25jHDd8mBw9wphZTzVgC9UhV+vFVNcdIwanEL4KOBlYqpMyVnLjcCXwVeBbwG36c8A8YCFwAHAo8CTgUfq3RgWNYXvf1wIvBS7IUOgdwzWCZwDHAU9EqOybIBXW7wbOBX6FOGzcwCqHw+II4GnA7sBsUxH/KuBs4K/uvHA4HI4peT6MISy8LZBuHuuRwIufCQ56GAmOVQd5FrAbsI1xyl8NnAf8RnUTX3d9NLLfDqyqQG/g2OTNvg6YmUEtyHIeLAFeiURUq9wDOVClbwKe4xTOUuXVLwZ+rAdmq4rgFwPP8CEbusybC3wQuLfNXrsZcQz6HnM4HI6pcz6MAc8DzgQuBG4ErkBSBr8CHDJg1qZjtNfbi4Fr2ugi64AvAgtcF+lfLuO7TdueRkUqKn/N0Laz6Ns2t8P+bQHwZqpdCTvM1b1INIuKRrhHaR/NR9pdhTU6oVddL9t3+0aa7ATPGWbgFCSA/0ztJztXdSMHG8CbfI85HA7HlMAchGm4to0O9gDwHnN+u2HioMsAytORVKygb6T1RquPfKZDwM/RxSTUkEhw1foDPwwcWUA5jTIKFe0B/Dyjd29Vrgn9eifwXDeqhi7MXmLWZtwmmh+Ktn3YrF0XaIOdqx1138RmH2VdG/TrDUi03/eYw+FwMLJO7WlIxNc6Sevm7K4bffEh4F+9gJZjEgGU2Qjl2eobrXTHGFgBPMH1xt5NwBhC+6tXiCYc7nE1ksfczWKwnpSFwGcr5gTIoknfZYxh9xQNx8D6qa7PRs5o/sUIPdcF2uAN4VfkOHjS83UizSJoDofD4WDkmELPpMneauQIRPydZicPh6PoejtSjds8umP4+/unIjut1odS8AnwWuB95ucqKONRzlLjdCiyFZ53GfA2NYarWIE5zN0i4HNqDCduDA98Pc5DqM55xj38fWukKIJHGQeHUAX6UN0nYzkL1CXAnqn3cDgcDsdo1cp5DuLsjDucy+N6LhxoznE/FxxF7BCAXZCocBHdcSeEueCG8CQ2fAOJbnxcFcGkght4ui6gZBLjE177EEIP/4n+XK+gEG8graI+Cjy6oi2iqowtuhBMc2lGhB2Dlx9Rwd5+W+qe8nZlDofDMVqGcAOpH7NbwYq8EU0nqcNBF/noRXXHWUg3kinlfKnR2+jhs4CP6eAnFYxGJarInmCeqTaJCNEYUpHtDcDlNL2BVIxmUUfo4p9B8hnr7qEsdYuz2PsQDgXjiNOomz3m+8nhcDhG92zohmm4jQ+dg+5bohZthZQ4NXpyfaoOAT6BVLhNKkzJTJBKa/+mzxUbakH6ytub9zYkSj7RA4XX8voHKcTDHJ+JFARKXHmf0j3CHQ6Hw+Fw5KerOhxl1wETN4S7M4K3Aj6JRA2rnOcWDNxNkcj2u4zRl3XlySdu6N/PQipJd9uwOssoTwYYYQ5zfShwCrCZG1wOh8PhcDgcDoeDitI1JmM0xsBM4AtItHCC0Ui0ThCe/PuB1yPNqC8CbgVuRiop34kUxLKFD9oZuGuB7yK9ead1QXEIdIUJpI1OhOQARDmKL/TSGK4DL9QxeHvOZ3c4HA6Hw+FwOByOkTGEx5Go6bNGyAjGRFsjpALv1jR7CwfcBvwv8CPgwtTrWr3nL4DLkKJTeanFgbN/H/AHhJp8h471k9Qo3WmAVOUQAT8R+Ks+f80NYYfD4XA4HA6Hw8GIU6NDFPI4pFVSPII9MKOMnFx7LQHeAfwM+ABS+TXpkNe7So1ZyFfMKBi3/0BK7x+PUKz/BpwLvBvJZ/7lJCjX3VKkN0Nywrfzti8Oh8PhcDgcDodj1A3hEP3bHzhZDaJR7i3bqlBWaHy+BfBO4CvADm3yZsNYn5saRzrkFl8LvExfN6ZXTa9x/fvrgUsGaAyH1lg7IH2Sp3tE2OFwOBwOh8PhcIyqIRyZXpknAXszdaOBEUJPDq1qjgXeQ7OBdStcBdySwxAOxuZ3EDr1uPmsUDirrv93ExKdHvTzx8C/AG/W5/H+wg6Hw+FwOBwOh2MkDeFAiX6uU2L/bwzHdCxeCrymQ/GqlUiOLx2o1ACrgd+YSG/Sopp0hFCuzzVzNEj6+DuBo9VIr/m2cjgcDofD4XA4HKNiCIfc0J2A04AZeC/ZLAP2zcD2Gb2Uw1itQipOk8NgXaXGcJLDaN4AnE3+/ONeFhWbD7wVoYknbgw7HA6Hw+FwOByOUTCEI/P1XcA2qZY+DhnLBlI86mRj+EYZub8P53zPaTnnKPzPdTnzj3uNGIkIv7CD0e5wOBwOh8PhcDgclYoIB0r0S/V7N4JbF9Y6BtjZFLyCjSOlq3K+3zxgYZsCXKSiwrcDN5r84kHSo2sILXynHPfrcDgcDofD4XA4HKU3hBOkPdApI14hmh5VU14MPLaNwTo955jPBA7OEeFNjIG9qkP+cT9bKu0BvN8jwg6Hw+FwOBwOh6PqhnAwel8B7O55wR0RKOMHm8JVUaq10eycRcnGgCcBczoU4MIU4lozBEPY0rFfADzOc4UdDofD4XA4HA5HVQ3hEOHcC3i1539ShCq8BInokorczgIW5KAPh79tre+Vdz7XMdxiYQnwSWCTnMa7w+FwOBwOh8PhcJTKEA5RvZcBS92wKWQIL1SjN/37eUixsTyGcKLjfiD5o9FlePZ9gRN8rTgcDofD4XA4HI6qGcKhN+6uwItShZ8YQpSxKtHoMEbzTaEri0XAjjkN4TrSpmqHnJ89i86060G0UxoDXqkGvztPHA6Hw+FwOBwOR2UM4dDj9qVqvA065zNOVWKOUhWYKXEv4XD/szL+viOwaUEDcV6H57aVm+cPuWpzyG/eHameDU6ndzgcDofD4XA4HCXCeAfDai/gzWrIjA/wvur6eQ8Bfwbu1XvaGjgCqbpc1khjZCpDr84w7A8uEN0O77UAibI2UkW30sb3zJLQo2Mkkv0s4Bzg/hb37XA4HA6Hw+FwOBylMYSDwXKiGlfJgCPB48CFwPuAvwIr1JBaBBwFfAgpIFXGCtbhnlbzyMJVc5G2SkVbUE3LSUleAGxVgj6+ocjaM4CjgTN9qzGK/bKz2Bqt0hpiZwc4RrAWRFGmkMPHftTmIUqdC2m9JOtMIOOro3rzX2vB1oypfnHdVmzU2NfspOVFO90xGfQ6Gu/QE/b5Ax6oEOW9GHg6cF9qcO4Cvg3cAPwOaStUVqyl2cooHAiPRijDFIxmJzkX2OZqCJcpWn4i8D1vuTUyimcv8vUjV4BGygBJptAzT1Z5j9xI87EfoXOgV+MY+bxUbi0kdGYgVpUJGOXQc5zlWEzX64W86IvuON5GGD0foSIPKuoaPucu4HVqBNdSAxgh0cYLgPcDHzZ9eylRRDgBbkSo3XbSDgK27GJMo5yG8tZI9HiiBIZwuOejgScAvzdOFkd1vKFp7+d0pAjcdkgRtyXAYmDbjH14p+7ni4FrkRSHtan3q3lbtkodZqPu2IhSSlCSwXaBZi2GUDtjczau3v+Aea8GwhBqFUmoZSgLU1nm0GasxpCaGfZM3Dy1Bh9IKV0PmnnoNN+OR67NrL0QIYGIGXoebI90uJilP8fAZjr2CbASCQzcBSzT/XAHsEHPhLjN+eOglLVwFgGPB/ZGmKOzdb5XICmNlzPcdp6Tfb65wE7AAbq+ZwLXA38Cbi5BGmKVjF9Ubs8D9lG9cXvVHRekXr8OuE3lw9XAP3RNTWTojnG/DOFYldqnpAzUfqOh93MBcFkLBTkx0c4fAP+BFJ4qC0U6MQL8bzpxofr2EuDJBQ/b8PzL2uQH2/zjfUtAi07PaQ14mxrCHhWuVhG9sK62Ah4FPAbYX7/OVSVoWo73W69OoZuAPwJ/By5BmB2xcXD5wVJezziq6Gyncz9b5dLtxuFXZQ95WIP1lON1IeK8XAzsgnRRmKWH+I6GlZTeBxO6nlfogX69XqvVQXQ9cI8e+nEqDaYxxQyAyJz39rlnI50HdtJx3xzYQr9fqgpU0mLsI2CVypw71Ni6Tsf9Dl27y1M6xlQc+3ZnQE33g90Le+v474jUO9lDx22mXp2wweyNlcAVOic36vxcqcZybGrTxD4npTsP9gO+qnpBlg6wRg2YDwK/MeuoCus+RlIw3wocrsab1YlWAWcDpyMOfnfYbCzHG8ZpuZeRFcfouRkcaHnsgYfUuXI18GvgXJURK4wtOGknZquI8KEq8AZpQI6pkLxQv9Ih73C5KtNHlywqXEM80heaxdBQgfH4gspiMKqXm/dutMkPfloqalEWD/9BCC38727wlB52fvYDjlUBdkAbRaeVohLyh4KSdCDNntjXqFH8fXWSBEdY3aeAsnnGZyEt9J6GpHbM0sPsZuBW4Gc6j+sqagwHZ2VYe7uqvH6iGlxLgd26ZNksAvZEnKDWGLga8XrfoIf7VWoQTJizuTEFopQ14zRFFaU9gEP02k5/7qZY55bAzjzSOXuNrttbVKk6X42wtan1kExxZTZW50NgdS3Rs3yLnAy1JCOPeLpeIKyKJeZ1q1RHuA2Juv1anUX42VCq82A68FnVCbLmO6JZD+dMJGD1+QqcDcGgfQbwtdQ6T4y82hR4OXAY8BJds1Od7WjZT3NVZ3wmcKTK9FZrKUvO2tzzWXptpe+1GgmW/gL4qcptej3+4WE+pTdXz+jj248rHPj3G2OulqMq8/f1dRMDus9O1wb9+lMV3ON6qM4AfpJ61jxjEuvh/Jw2YxLG48DUwirLFZ73fV3kRju9RBS5u3LObRjrFcDjCjpFrNNpJ+C/kWhKuuBV+sqzBtq97kHg6zTZDFSYOTAN+GWBfR7k1hlG0Y9KtgY3Ab6cQ+59iiZlNaoYDTfIpZcC31UjdXXOddzNlbUOrtPz7JWm4CEVGs/J5us+QWXOVWoQDWrsEyRl45fAf6nsYwqMf6f52AF4J/AXJLrXj7loNzfrgYuA9+q9VPVsqBn6/t8K6NVhPN5VoucOz3KE7tG4zTln/3a9cXhEJV//i5EAW5DLcYdnO0MNvzLJiTBP/27uM8653n6oztsic2X/7wXqwFrbA70x6fC6qxC26Xgq8NKTwVuintIiRluvjKW71MuSxxCeAZxVIkM4bI6HaBYZCxG044CHVQDGBcfkeoRT38kQ/lAXi2wQV3jmPxkPmxvD5TGEo1Qf6lcgNDX7no0+7RerENwJnGz2TOSGMMOOkqLGQXieeupQaugzhHl8XQXmLkrJn83Uu39+C9nV6JNMbZj3T//tauAzSGQ664weFYNrOsKS+g1Ck80a+0Yfz+qs8/gm4Bs8kvJZmwJ52SDRrvekzoB2eyEuOEd5jKe0oXgj8J+6V6tmEI+SIRzOhONN0CevgfXKihjCz28jl7MMtBUIjZqSsVIHYQjbvy/R167P0P37cXba+TkXYTH3RDaEwfvXAUeDrdJ4ix5A7RaVrZB83hDutdMz/FnvcVzHdGsklF/0PsP/XtDGgIxM7s6tJY0Ih/tZjUT7p4qHvSqGcM3QoL9lPmNiQI6wOOXI+hFNylXkhvBQ195W6oiLO8iuoCDforKorHMXpXqzvwypRxGn5qQxYDlqnQp23dwFfAzJU4sqbpBZB8QMlU/nqOPYjn19iGNv5dAa4MfAk4xBPDZiZ5edk7nqELo6pYO0m490AGINQjU/F8mh/CJCof01kgKwts1rWzlK7f9dhtAtxyt0PoySIRzG/TVdsMHOqIiT+1M5z+/YsKHekOFgHXVDODI6z0tScmNiQDK8nrIvTlI5NmmnxDjw8wFHg9MR4cM7HPg2cn3tEO613UJai+RU2ol4d5fGehAgn9Z5yTIgw1i8tsCCH1akPAFOqTj1ddQM4fC356nBkwxxP1nj459snA4QuSE8FIXnpakocB7H3dNLuset/DxMD/xkAN7rbuVlnDKI34/ky1ZRflolcWfgoymjqFGicyt9L2uALxm9ZFTOL/sMTzJ6X94o74T5eh7wASSXeHukyFn6s3ZV3eirwN1dpoklCLPu02YvlN0xNIqG8Ou7CIT8GMn1LPP+qSFMnKRARHgCSfsbKyGFvV+GcM3UYPgMTTbPMM5Q66RvAP+L1PToSjaEB97TUB6GEU1dQbOoyFiFDOHw+V9F6F7hHo8yFRDjLqOorWgXNVOS/Bclcgi0U5J/qZvHjeHhG8Lh/f/NCLJGiZgV9yARuyrl6Y2KITzdpFskOc+EIOPeXdJc56DInWwU8TKmkrSjkV6K5GBVja4bxv+ZSN5nUvLzKuv+7kFyZueOAFXaRuZPSRmmeRXmcJ6/BGGOjLUpeGMRiij9vAtqdZyiQ+5VAV1iFKnRbyoYEQ5MyRkln69ZakjllU3hfz6WURRuVA3hmkkp+lGLvTmsszLcwx9oFnuOigxY+Ocjc7ZD6ddBOctMQqvqcokpq72iBP0r6zqOFwMfUaUxRujMp3SReG6f8yaaVdGSFuNwJFKRucwCJgjQx9DMd3YMvzfkCerR28SUos/TzqtVj9Veti/YCime8yqavVodg0FilNaicnxWids/fQaJrG5t2tFFFWorFFqWfAWhGcYl3xe2n+RbVMk80ChntYrIybrKow8gFdKXVmDsO1VI3wz4tjqutjatDqMOsj9CHKdvRJhE30SKjTUMdTzKqAhb07+vQQpwHQd8PLXG8+7lGInQn4EEb/x8GCziLuRmoyIOu3mTOC+ngt4YI2lF/4MwPCZytq/tt+4YGXvsSOB7SAHWJA9NumZuchxJFB9mY/kaUrVtLMdmW8XGebHDEgjjSOXbU9VoDbnB70WicnGXylaE5NnclVEaPLzfJkh+wuZGsSuzcj0faUPi0eDhC7OXINWA57RR6pKMgkhR6mqkcsl6dY8NNao+BbzQKGqO4VWSzSsTy2YEb6kG5GvM2TJW0ZY2M5GCdj9AqumW2SAL6+dtSNRkfspgqsrYj5vI5eORrhCHV9AYDvJ6J4Sq+lwTSRnLoehH6gg4Asn9XaOvq5n3bqU/xkZHqSHU+LciUauVBVrrhHNnAnGqfxvpbR/7+TBwB1G/z5JhwFt7tj/bN0daS/2L6nzjLebW5vg3MvRGUn9PeiirG4iD7FNIQLKjbVQzi3oJ4ukcxoKNdFCmqSHc6OCZDD2H/zHEJPXghVyJJGmfbRrQvw549SSMYPSgOKPNwZIgvbqOqNAhkCD5SInLlKH2yXsycJoq1fWMtZOYPTim+zI4eNbr3luvQmzMtAqrtekpTJeRi5nAh5H8s9idKCNpPPfTCJ4HfBApBJQUjB4lGVWys650ewf6zKyJkcKD30d67MYlNdxjpIfoqUamjBUY+yTH2DcGNPY102N9Lx3751RIJoX9cIDqFY81917roPyGufs84kC9PGX8Fhn7JKWvfAZ4MdKTvIgxPE0/ez91Cj3ez4eB6nGjOs6+flqPy3QkPeRZJngaZciLsL/HdZ8GXc7qjlHq71EPDeJw9hwBfAIJqLRlf9kH2Ztmxc9hLsBHIVSdezoYwyC5sW9GPP6DNAbDZ60A3o5EG8LB/VKEQjXWpcAIysIXkbYB6cMh/LwAeAeSd1Glw/hQna/lLluGoggtRYrVbGUYDaSMhGAATyB5TZerY+Z2hIlRM2t7EeJ120LndrceHprhcxYDnwOeiqQLTPXm9Y58a302Qv18aQfqZ5KicPayh2yS2gNRj4p+xQjN+BtI7u29BQyJQTncwlkYdaCoZTkoejFevR57zLm+NZK6UUeiq2WWScGAf6Le864FUmHCens/kvr1kJnfyepQ4d5+puN4BtK+Ke+ZERTsHRB207OQ6rV+PjgcvZcfz0cKpaXtjdjIiSBT7kBSIO5UnfE283+xGqfbI4zE3RDH3LwWLJRubckYSf+7S+20lkyGcfOHg4eczB4G8EA1hu/NIaAvQ7yBrxmQIZwYGtEDSLXms0wk+IWI13RWl3kr4RluRML6jYzJC0rFR2ly4KtECdoCoZWdbTaYY3Aevffr/rLRmTRd8TqE+naeCpF7c+zdcWBbhFnyPKQI1xyzXrtdp4Etsqsq1a9SozxyZoGjA56KOErHWyjXVp5HKWfkel37lyLMow1IKs5qs45jJD1lsRrdS4CD9GAPTIooQ2noRbGlmt7To5FcyxPYOCd32EbwHgjrZFqbsznOqAwfKHX3Ia14bkVa79yj+361OTfmq4xZhNB9t9fxn9Oi00KccvZNlmK8FcJWuRRxEpbRAAtjtTNwusrRvJH5MEan6LnR6MMzBubRLxEW3bd1zeQ1hkPKwK66D14M3O/G8EAcjR49nTpG8MGII2y6mfu0Xjeh9tg31Ya5HXGcdcKmqjseoLbcwSndtBt5HZnXvxUJ6JzdSW+crf807EqOdVOFLe+DbqcHUb/7CdsmzlchFF9LV3sqxdsCtOqn+u8ZFX8j8/Mr2zS4r0IVzk+nyvE7+ls1OgiqV2S8T3jNQ0jP6uMz2l9YumOrK43FSMXL63pQJTbQbR4CXlRiCtOoVI2eZmiLRapGJ0il6WE+RzB+Fqgh1Wou6ql1eRfwR1X4j1ADd6xLA3W+GoKvAc4ErlDlPE59fqOHrSOeWyKZOhdxELca+0bq9w8i1aRPo9mCZ7zLuZ+mjojnI87iC4BlGbKz3sOK3u9tUyW5DGfIdsD5Ofv32nXVQFrD1Pq8p20k6SXqhKoXrEzcMAGCMrXdG8Wq0W/sogPKHyl/1eiidpBdc6NYNTq8z3ydPys/0v3uv6BnXqvzuJahQ7ZqCXuYzsODLc6LpIv1d02e9oPbG6WhXgKDaRmwS4GFdQDNhs71PhpwMVIoY7fUvT1fvR9JDybsF0jUNB01CN8fod7xuALtJ1op/ue2MaAcvTWEQyucXdi4uJxdPxcgrYpmtGh/kYciGrXIN1uixtE9k9wf4XVXItGfMlb8dUO4HIYwSF5wqz0T5mY98DukHcieBdZ3p8M8jc2RivlvAM5BGBa96qEb5uZzQ6yXkT6jnmPuK27Tkug6JIfryRoV6DT2URdjP45EiV+tTomrUud53APH/Z+Q6HDZcuSDEvv9Lvr2JsB3yJFf1wdj+D9a9NPudM91PfuOLlGLq1E0hP+9i/ZJbghXs33SGJKCaZ83fF2FdDDYr428LqI3pv/3GOBXPQqkJAjLtq08OxrhdJeht1+46W8VGEwQuufve6RgZAnhaxB+/IKUwngSUj2xFxN1hx7a6Q0VBNBSmtHvqhnB9p5vVAMPN4YHEhGepUpg1r74OpJjRY8V6SgVUTscaTGWTHJfJghVDzeE3RBuoQDsoXsg7Sy06+53CH1/84w1G/VQsU9HleerUfw+JPUgmeRBH5TqX9PMsYqGXGH5Ry2ep2HO0rdl1BOo9cjoilLGMiZSvYcaxedksAK6Pc+uQ9KUynKeRSY6/vaCMrdh+r5uNeBnCvM1m2Y/17iLvXAB0h6qDM5SN4TdEK6qIYw6iJcbp2Hd2CovMbpCLxkYdt9uqo7quycpp2MkWPnoDLbt/+Gl6h0vU2PkdeopzkP3GjODdpq+Nu0pbGUY2+hYFl1tNVL1cmlqohepN6TRA8M0vPbkDGNkzDSw/lOFjWC7tlYXmFs3hCdnCAfP2vqUIIsR6uasPlPJaqkm7P9rlIG4SwfVMuNIidwQdkM4JTc/nkGnis3XTxslnxZGU6/vbSzj8N0MKfDztza04TzKf6xnw4IhrqGwfp+A5PLGGVTwBKFM79An50ORsZ+tAYDvmXtrFGSUhXm6FWnhU7Yo5FEI+yAveyzM13LgkHYK4wDOvd3VYdKtMfy6kshTp0a7IVxlQ/jjGWk4l6gzlz7KvHQg5Wik4Fa3rN+ga322XYD1kyWiRdsF9g9gx5yDbf9+sCoGa1oIynqq92nW59+og7Y447Mep17HXlDbwgR9NWNywjMt1AhGlY3g9EH1ppTS7eitIfx4mhGos1Nr7UGkncygWgakhdoXJyFvwhh8zZTed0PYDeEgK7chu2ZEXQ20/8qIQA3LYB8zX09CWsjYtREXoEZ/s0WBqEEbwh/T+3k448z9vHnm2hDGP4uCV0Pyq6/JcC7kPcv+RnY60zCjwfNo0gonCsjWh83ZMKxnCZ/73C4cQ8EBc3GqCq0bwr0zhN/kEeGRNoS30efYS3VJu2bPY+Nc22gAz2LTQm/q0g4KcmENwt55BPtxJtKCoYjAHGRk+AdI4ZI8gjk9MU9HvP+XIjmKrRS6FcC1OslfQooKZRnAC1UwreiBUWo95r9Cotn2/mvGM3puSaL1vbg2GM+MU6P7YwivNIbw8QhDIigUqxBq4DAMAft5X+pyTYdnvA+pDUCJjGE3hIdvCD/FyOf02npTwXSbQd43SOXbT+naTjL6GMep3wUG01qTFzk+xGdYhBQGS1LMk+DonVZC+nBYB1siuXD/zKDUZY297WH8phLt3cgU1FzfRV7wOUjV7TIUvJsJ/KSg0zQ2jphjSrDeRpUa7RHh0TSEz0YqOKM6utVTLqFZS6M2pLV3AM3IcKPLINyXaFHd9Y8liwinJ+ebSH5PXuU9regsRvpUnYjkJr0bKQV+kh5i/4JQmzZLKRJh8DdBCmL9qQeJ2+lnO4ONc3Hsve8HXDgikeC08v9DmoWcvAx/7w3hQI3+WmrcT9M1XhuyorM5Unium7UdKIwfHKBn0g3h8lOj7eGfNmC+1KKdESUziGu6d7+oTqs8jsW3DVnhD+fkk1PrOjbMrsUllvPWkbYXUoPg5pyy6AzVG8oSDQaJTt9cwNEY9sldSC2HMlGK90Vy+7qpHHuyG8JuCLshXMgQ/gnCpNgPYQ6GfXcHEpEtwznzOCQ9rtvg4MPGoI+s4L+nxBHHhikGskMbilMrOmbUxSKylLVHAz82OdSNHuQD182i27QFVezZSP/EMjooekGNPr9EdLJRM4RXAYfqa9eZ152DUKXLEo3ZE6kCHRdc4+F//46wNMqyhtwQHo4hbFk0X0lRi0ORjB0rIGvStSEOQ1rz/BVpv7RWn2sNEvU+H3haCdZO+Ny3sHEbwBCxfn5Fxt4axDsjtVP+gETo1+hzrUNqXFyCFM+cX8L18+GC+lyYr8+XrPVQmI/XFkxDC//z5RLsDadGuyFcJUP4HNXLP2vO/oeMDJ9Wkmd7yyTqzCRIT/WNzqTDU0pDmY2n6xC6S61AnleU0W4hSh1+aYN5mo7Lt1pUH5vscySIx39mBg9+OlKMYMOIRYLTwuN2hArohnDvDeHVwD5I9Dcx3v4dS0QlDgrKcV20ygiyai3wwpIZkG4ID88Qnoe0nwuydsK0TaDE0eBWOcQWW+iZdDxSqGRxCe/9I6mc4BANXlghOZ+1PjbVMX8eQkHfJ8drhqUg7g48UECfC8rk3UhF7ahEqSZhv06nme9cpOjXd40sc0PYI8JuCOfr1vNUJJjSSDnIohI93zjS8aRoADfIxctNEDIap0kHbpSs8Ex6A8ZIL9QfIJUnP430Dn4ox4GUtBCysfl5OhJxfhLwROBYHfA4I2+3KBLzHKuQ4mSnIVHmMR17kAjZG5Fqvuhn10bUwJuP5CJc12J+HN1jDdKG67nm4H0nUmigZtbbMNHQe/mBGoIvKrAOIn39bIQmc6Y+o2NqY4ZZB4murwmkRkSWzC8jErMP7Hl2H1LDImsvJCVRTmx0NNaz7QIkml2rwNjTYuxD9L3VWZaUKCJ8gip4SQ6lNTHK7ZmqT42XSJaG+9uA5G8vRZznnZ4tMTpdvUR7xOEoO7YAXmxk+dVIr/cynZ9Bp/2E2mrbFbSVIrUlH4ewfWvjJaP2dBLyCVLI4aU6AOch1ZQvoFnkogi20QHZFaGY7QdsbwRnL5wDdoLOUwP4J6bnYl3//gwk53Fv8xyjHCmtGw+ho7dOhmmqOCzR3/0B6e1ZJoUgMV//A4m0bJVTgbPPeiASHbvZFZ4pj+k0+wKHyOp6vaqIpEVxp7SXuyyyZ0HG71eU3MnezdhjohCUJFDQUDl4bMqIzKNX3Ueza0VcwnmIECr6exGWyuYd1lSYqz8bh5ifC/2ZF8do6Y57qTEccmm/igRQyiQbwp7+B1Lo+Z3mLIxyPudMJFj0YyAZp5z9ONs9RAhvb4fw1o8HbkHaH9yok3YLkty9JmUcbK2G7o567aqHx6Ypo7PeovdgUQM40fdYg3Duv4D0HJyOeDnrCJXp3cBz1DCMK0Lhmyw20flw9F6YbW4MgnXA5xC6XNmiMkFw3YX0qzu1gCwKys1BKsNu9umf8gj5szayWutzn9phRIrLig0tnBM+9oMx2o806UZFxvwshCpISZ8znBPfUwX2VMRp2jB7PDJMo3GEhfDrEj+TG8GOMmI7s1+uQNIL6iUuMPk5xPn3qAIO1xCcPApJ21k2XkFjJDJU6eD1D4ZtLw67aJItKBJDCwOJAr8DaYGEofpsArwAiYbtMMJU6HYenQUud/qGsD8uRaqdlzlaGiG5OSciDI2iNJc9gN/4lE95PKiXpc/PRJgRrrzR91SH2zKccnsDs5AUJmds9C84MB0pkDijgEIY6bz8pGQ0+3Zn2teQYMepSN42GbUn1iPFdK5yQ7iva87l6WjObdC/fgHcWdJ5jpHg5t1IV6EPd3Gf2wdDuGZ69FZtUddSOTpJi96LWT9nUcuiSVZLtIb0GHA9Eul9phrBQbGfg7SZOAtJQt+BqUGFzhKiW/lB1ff98V0kL73M3v4EYXP8vsv3OMbXkQOJCD+QEbU4Fmm/F3thvr4WZ7kzlR+cAIeogeaKc39l6DY025tEORVJEEf9hRWQn1ZP+5PqVe9C0n7uRiLA9+nfXqjKceRrzuEobGCOIc6mb6TYd5QwvRKkwNftBe8zQXrH780IReWi1FVj40rRtRaVo3shKBspOvPNiLfy2cD7kZ6uYYEdhVCkz0JyIhupYlxT6eCmIsVTqjy+DyDVGqMKKNIx0lt6ZRcU7n1Nn3FXfKbuek/UGAspKWEdHYJU0CTF1nH0NiXj2pQTLkEqeb9BlY4Yidj5Hu392O+IpFkVdfb8Vs+JqGJssvuRmirPRap5/ytS6PRZCLuoRjXSCZwa7SibIQxSe+kmU0i5zOf+MuD7BdPq6ghbbH/0Ibfwue96wTRolue/Eal+ew5wWUqR3wt4JVKNbTNjQI95lVdHHw+q85Cqf1VRBi5Ccv0PLXjPmyA5Iuc7/ZKpHJWMVbF/LcI2sUbB+/Xn043cjo2c9jUzeYXkcqRFzCGqaIzr+D4LaXX2NuAek7Mdu7HSs7E/1KSM5TUmlyPR4Ko54+2+XoH02SajeJijv4Vr3RgePVkyjqRL/Kwicjnoe39DGGHTCjoQFwMzaojH1lG8CFZNB/1apH/iUQgV+hJzGO2NtHn6A9KEfDNz8HtUQpRVpyr2z6v3C1UIoop4+R9UY7hoZHcmkifsPamZ8tGxaxGaFCkjt4Ywdb6ma2Ui1SuSFowhRz55YwsURRkpGicA3wYer+NeT1Ve9rGfnCH89C5o0VezcWuxqq25mEcyASM3gj0i7JiULLnVyPGq7KULjCxLChjCi4AtLTXaF3a+qpFB2F6uitXTgP80ylcY3PeoIfJGQwvDD/mO/Z0d9MRjux74S0X2dmLoKucixeTy5HtEpkro490QnvLGmG0FM5ERuYgRVs4vEAfloUjNhlkpJ2fe1kStUnJ6nX5TJVl+BnAvj4xONoAnAL9Ceof/q56T0zOiw5MZ+6lkUIdn2wxpI5dX1oexvQ6psl6rcJpSujaM6xQOx+Tkyd+oTnHDcH/LjQ2WFKhrsSewYNy9Zx0HuWGqSE+oEvVTpErtLWxcrXAPpIjDi5F8nfCacVfQHQyueusYQs+/q0IOh6CIna/GzDY5Pc/h2RZ63rkbw7pevgW8DqHLW9pncLZsjzgoX4TkFF9g9stKpLjcCoTOuxrppxjncOQlHTod1EZYaY+NcfVNhAZNBl11JtIq8JlIDtp1SApHMMpWZIx9o8djn4yInIhMC7nxgk5HdNwbhsLucHjVaDeE/1axuQ2deM5HagYUqY69EFgy7nPf1qAIrZTWILlnZyJVCe8y/zcLeCzS0/gJbNwKCfJz1j0i7Ohl1b8LEapiVLGI3u26v7YpKLw3RaJ7az1PeErLk5qugbcibWGmp5S2cUOr3EyvR5k1+ADiDX8Aoeov1/e8W9/jfv39BFKkA/2fh9WIXoP07q6rIVfXq5Fh0E1L0TyTERj7BOn3+q8ZbavGjHN5GrCbXs/Uv6/RMQxjv0xfc7e+bpVedSTXGMRptj419hM6Hxv0b3nGvsrn0R4FUq3CPN1BMw3FZaWjG4ejY/RQR5zCSQUdM/9UOV8rEERJgJnjnqvacnDGTJ7lp5DWLhOpwX82Uqr/qcDsFl5XR2u4I6Z/uMmM8UTFPJIXI1GOIoftlgjV8gY3hF1JQxg7H0bqNiQZeas2Qlgzv9/CFNEgp8M0FIZap0b4CjXAbtWf71OjbhkS+bxHnT1rOuyDpKJjfzFwEvAd8yz263iq3WD421y9titwVm8wvWPXGIN4lRrTt6mjYoUa1NeoEfhgm3GvytgHSvMTC+RuBofjrUg+fc1ZgQ6PCDsUd7eQjVXALYijemEB+R0B247rwbGVL+yNDuVQcferSM7TBvN/s5E+wK8GnpKhBHgOcH7c5wZLX4rWrDOtTJIKMgQuLpDvFpkK5LO93oHD4HQkWna8ifrVMvJMi1JuraE6RtNpOk+vrfXn/TNeu1oN4nuQVns36FlzqRpr6fzYqhnFwbFwFnCwGsRktPVpdU4mHcbeRp5rpvPAHL226nB/t6oT4jYd/z+pvLk/gx5c5rGPzJju1EURowfUgTPNadEOBx4AbNY+WlFRZuky4Eo1hPO0SQyycqdxPZi9CnRz0C4EvoKUD7cU6HnA49QAfjKS65SYnEyPABfHWjeE+6Ig3Y/kPlbVEL6igFJno0le+M+Rpki/HdicZtSsU5/VqMPPWZGRVoZcnGIZRcZY3glJqQnG8UokN+sCJNfpRqToVFLBljDhWd+BsFHebvKzx3Pu58mMfZJRSAn97O31eoz+7o1qFN6M9Fy/TMc/PfZlo64HQ3jTgulXQc+5xmnRDq8a7UhhvWEqVU02rNNztGjl6KXjCG2IKV5YCMQj/x0kv+k2Ns4BfjJSWOU55v/r+v34AHJnR1XouDDt37quV/j+70kVqcuDBTQLZjkcweC9BXgB8F7gZQhroN5Dud3OcK51qHIbDPZgHC8GjkMYSH9G6N0/Q7zcYT80KlTJc0KN4XuA9yH9vgc19q3uK06NfYgkL6ZZef6PSJT4p0i0vm7msmxjP7uAIRwMmDrS5tENYQfeR9hh5vNWpL5CFW2JDUgQqKhcm1Nrk6c06pMeQufLgdMQ+tzpKSP4CUgF0u+pgjJmDtHxSQqCJKOKZZxB0Y4yCqokFT/AXID2VwG9D8n1qFoV5WSSlHnPdXNk5awuB94AvFIP+vEhFqgKrX7GTDeBtEyfDhyN9Kf/MfBFYF81YKqigNr7/BxSPOsiYwTHQzp3Oo09wJFIsbUfA18HjjJrpWzMr/k06eFF9sVaFw8Ojwg7eGSO8ETF5tcyepd18fotakjxjqniGUyMclRDKkE/DaFu3ZDK9foQ0u/wuXrQ9KIPcJzxPlk9KNcjdLm1NCuUZvVIpIKtIBJDa7vXDWP6RW95qML3P1HAKxmZ9T/P15OjjdJ2BvB0xLFp5emwZWhWbYkYcezsCLwKiQy/Wdd4UpFaFIlxUP0KqQ79PpVNtYz0pDKNfaxj/SLgbOCzSO53XBIZExkmzIyC97QeoYJ7uzmHw0FG6gQVDa5t6IIavcl4xRXmbqIDNSTq+wFViB5EqEUTJgr8Ppr5W/Ue5ADHppBRwIMIZew6hL53AXA9kq+0ztxvguQjb63XvsCjgZ2RPLMxQ3caq4gREO53pcudvip3VTZeViB5v0V6Cc/wqXe0MYZrCM34xcC3gVcgdNhNjUMlLokcraUM4m2BTyDRyfciqTxUqEL6mJ537wF+qGP/QiR/u2YcYGWot2Fp0A2ldL8ecZqfpPeflGTsZ3dBNY9Vx3A4vGq0YxRamoa12A2te/Y41SyqQ5e5wLEav59CCpNgjODNgP+n15wUBXoyi6phaFjLgKuAXyM5SLfRLFrRCcGDe7Z+3R04VBWjp9DMj6yKgFpLMyLscPRCIM/wvDdHh1SUmsr7nyAt8Q4CTgQOB5aW1CirmZznYxFH6AeBLyMe8CoYw7a/4z+AtwFnIq0Hj0X6CU8zY18rQXQiMjR6gB2A7wOfBN6JRFZrQ46qdhNNbzg12uHUaMcI6osPdcHYiceRnnqMeCR4TJ/zfUjO73oTIZhA6GefQTy+ttBKNMlJCQfpdQg17IfA3zMOoaigdz9RA/oapMDXgYjH+vkVKGQQ7i30enQ4emUIT/iwOXIyg1A5/CeVydsiaTBHIM7FGTnWYjSkCPEi4GMIY+LjJqcrqcDYh3F7GClEdR7weR33JyKMrO1LPPY14C1Ir+NX6DlWtb7l4wgLwh3RjkEZw+6cdjCAiHBXgctxhKLbGMFKcIk5xC5GCqVcagzgEK19DPANYJfUayZTqTSM4Y1IAa5fIfRnDE0sXSyLjNyvpIMiEBSKvyItH36gCtJSeludsx94CKHKUUFFwtF/oTanC4W37jnCjoJKWQ2hiV4PfBhxiO6J9AB+FlI4aVZOAy9p0/4n6qFRFquh/l793cd17VdFjiapMbkDoap/B0n32Qt4BlJga27OSH96/Ps19iGf/HiERfYsdagMa+yjSUToHY5BGcxzKiab/Gys5n3P7uY5xlWI3wksGaFFYA/aHyE0rOtT/QATxPP/LSQaMNkcW9uK6W7gC8DXgNsz+kA2ch7s7XoYJqnctxiJON+iitERJTWGw3M8gPew9hzh1vc/v4uKgav8MHPQXYQ4XGuRCPHfEQfpIsRZujdwGNJmZwtV7MaM/M1zPsQZDKCoi/0a5P1MpNbFQ8CnK9ZrOJ27HYzM6/X6EXAy4qA+GqGuL0HqZNiWQXnGrpGiL9vXFGV+RTrOE3pf30BynYdFUa938ZnjwJY6zu6EdgyCGj29AjnPm5T8PgeBaUydYl9hHd8f+ghfr4dMXOGqYWlDK0baTrwdoS+NGaUnBp6nf9+sBwZjMILvQ3KQv4UUv7I5yA2kwuOWwK5Isaulqc9dj9Cor0XafNxqFJtWB1aIbIcD+hLg1Uhk40kmSl22+bnVDZe+YTNgK3WKVFHRmV/CNiWO0c8fJsUYelj30C3mfxcD2yDpNFurobyTKlGLTPGicTVUZyLR27EOZ2u9oHFcMwUYT0Giqj8sQc5qt2MfpwzThuomyxHGEwiddxc9NxfqWbq3jvm2Or5zVJmdpeOeZ+zjDIdIlMOYbCAR4XcgOduDjMqHz7hfHSELChgoY3hhQQcD7SM8qwJyqWZq7UxVVtlWFTxDbHBxQRfz9+A4Urn37hExSBJjUJ6qh1NsDtZgBB+JRGw3y6jm3I1nbAy4HKkoeW6qiEbwHB8D7KfK00KkWuZYiwm9TxWA84Hv6ntOpCjT7Qzia5HKqGchnvRGCR0cd1KdQi9ULE9iNk1KYVTBapRbd2EIb8AroTp6c4Y0WuydBGH43E7T0TlmDK9Z6sSZb6JuW6rRMV/X9Rw1muci7Xk2QXJi5+akq0UpxS04WD+GOFGvqLhMjdvQflcAF+qFkXXTdSxjPVvn6Nm+pc7JPP39fB2XbXTc5yG5vpt2kDdJC7p1uN6i9/TzIcjbtQVqI0SmqOABwB8qqvQ6hqtf1LtY5+Mq41aWWD7NNy0Yp+rcLlB5ur5i9x7suEVd6L0rxlWBvG3EJvQDSL5Xkir1niCR2C+pIZpMIvJkjcvPAKexceGxGMlxegVwSAuqZ51HeqTG1CuzFeLtPk4P2VNoesbbHV6BKnov8HI1hvcukTEcFuhtRkB6kSN63lJjboXbMiwusC/D3r6P0XHoOcqbL2UNoGA0P0SzWuWd5KMJTtczYa4aYnPVQNtdvx6M5CqT0ePWRiwD02kpQiV+Bd21kKjC+KejtaEN0DrTii/P+M9RhXeeUX7nAvsgEec91FCclhr/OINWHfoNvwdxXA9K0Q/vf1fBCtCBIban11NwMFjK6qySt8ycp7J3Ku+LcCatr2gRwJndUqNBijqt1zepYsGsxNC6TwE+1KLf2TzgI3rYTcYwDJ+1Fsk//nzqsD4Maa9wTKriZJI60MfbUMUS46F5MpLzeyrwOVX62+WDhfu7HinW9QU1joY9t8FIXwVc5kZLXwzJBpLDuDvSIqxWsbzBSPcnXeTKuUPFMUgaNRnFmdLKQ5IynBPE+bwBSdmhBUVvBuIMPQRJcTkCiRxPy8jTC1TFZyMFE384okybrLGP2iiu6fMuMVHUtTSLNQb8VP9/uhrLuyDtnY5TR8PslDFpjeGDgZcgrRmjAY3FeId11M4QXuznr6NL58u9uu6m59ApI0ON3oKms7rsRTqnKharnXRfBQMom3TpyLguCPObkOJFVRSM1gj+HzUWo1QeQxiotwLPmWTebHjtVUi7jc+bQV+KUNR+rwdozRjANZOr1K5AR5T63yRVJfQ7SH5ao817JMZ7fRbwl5I4NxJTJfTKDCqcozeGMEjPy6qNb9inTyogi8L/rDTtQFy5cwwjxzU2hZliI/vD75MWecC1VM/iGIkw34LUnDgRKdj1CuDPNL31aRrxLISFNG2KRDWSjPHPGvu4hQFtC3XVzHs+rPrQBXrm7ovUFDlDjc5aC2fIW1UZG7TD+foC8x3+Zxt1tNS9HoNjAJXK59JsixaV9Hl2msJ7IYzBnirDqogdEcYvOecxyPCba0aQrqqwITyGeMHfZGhhcYo/fpj+PZ7EZgwG7UVIpchfGeX9OXoP/4+mp4xJ9iMmo93T0Xog79ThwLX50p/TcYlKkv+1UhUNz0+ibz0vH6WKcaMiCnHYp3MQamJRQ3g5UjjG15SjCoZb2ohrZKxba6zdhxRhPA5hIaXlZ9gHRyO1KBKnveYe+7jD2NeBXwAvA05A2jFGqc4NCVKw642TbMHYzXn6uwLzXTNK/4EDvFfH6ESEV3bBMpul+6OM6y0xhtRUl5kzkMLJVXKkhvnbrsuq32tqZmFfW0EvcjBML0UKVqS9teGAmgu8j2ZFsdok2mz8GXg+8A9zD+9G2ijsbzz/vR7HUJSrjtDlvoZ4/pMcHPjfAf8sgaMjjPsl7omm3+XjH4MU56nKng779oCClf/C/9w3ycJ3DkeZo81B/i8DPgu8AMkPraUKQi7Q88kNnN5Wsw5n748QCvQ/U/TzwBT7F1MhNxqQAnhuRr2RTqyhmXSXguJwPFhwvYXiWnuVPCJ80BRnKQZ76ukVddCEDgJ5ZG941glgeaAErUWqTVbp8AwH1RqEjnxri2hQohN7+CQM1DBo5yJ06Btpern+B8lLnmvyjqM+J4THwOOAd+XsY7kWiSYkQzSEwxiuA77ttOi+CvW6GsF7VMixFe5zd4pVbgwG9BVOi3ZMgWrWgWH0ayQy/HCK1ltD8lXndFnd1UHb9hzjSFrUCTRzjJNUetQ+kyzEWVQBvJliVV4DVfwgU0PC14kj73pbocZwUeyJRBw3lGi9BSbadNU9fH7h0Ar2U94MCf4ULZR1BXCPzY252NCKk4q0WaghObPfa1EcJNEBepPpmxd12SLpQuDfkMhThFRX+4L+LjEU7UEu2hchdJN2Oc/hec8vifBZgbSacqOl/0blU1JRjbLnNk8DnpDq+Z1nb65X+eXOFceow6b2/BA4M1UgMUEor4ewMUPE0ZszNzgXLkdYZrWUQ24LxOk+yPOtjhT6yvuZwVl/CEKDrDKNPjLOoVoPUtEcnfEQxVoV1kzEbteSBdzCfRyBV4zGFMza35wpVdB1tzGV8IvkB98GrLQVZf9CuSu6kdG66EYk/zWrkX0YoMMRD3k3Czwo4/ciub836iDPAT6OUKQaQ9g8IX9pMZITlq6gmTXhNyJ07mHnUF6kgtT7B/dfuB+rillUcuEelMgdzF4tgnV48TXH1PPcr0fqRTRSPT5nIZFJR3/P4G8B15izLMie/RHH+yDo0ZHJE84r/yJTUPGgCjqloxQLolVhNDeI+yN37gZWFzzfG0hxtoNLNjfB0HsawkSbyiyaUA9hU6QDARXQHcOaPJhmDnoRh/LdwApbWXk5kmtbJYH4bTXuxjMqaAa8pkvjzyobb0AiqiFS9Rqkgmd9SB5IS+d4dIdWSpg88DJEzX7l58nAqi9vj1D5k4oIswOMMCtyv7fR7EvtzhXHVNrnFyHRybRjcdcUpdfRn7SsH2W0R9x0CLUKbkDyx2s5ZGBg4IwjjvRaheSmdTrMQZy9nwO+r46Jk9m42KIbw/1JvbqH7pgshxqDKyqB4TeBsDsPcufJRvLtmaqLlTltItzXbL3fIgVWQ+u5S2zkyHoVy+4BCDTgy5Dc4Kw+qeG59kFoYpPJC/4o0oIoMlWbTzdU6GjIxsPSDr3PEuMIuHNIxkI4kO5Bio05BjPeqICYWWJFJ0opNTO6OCR/54eYo0MbulGkTCZIqs5fUgwmEKrY2BCNATv2YyNYuCs8z6UZitkWpufwoMb+cqTdU5TT+WELBO1cIfkZ7vFIJDjxI+B1SHurE4APIeygk/Tcc/QH51K8tg1IbZuFJXOqHKEG+sN0l/vMCBZb3VNtnaTksiAwY4/oQj9eGZiEtZS35lfqISn7ARQh0eAHW3gzw++O1U3XKHgQN0xxrA+Z91uIFMeiBAdHeObpOSK8Y6aoxjAM4dgc1rf6GdL3cV6G5LRPAI+nWSiuzPke+wFHdZmXcr5PvaNF1KhBszXRKFEmrYF7f4ZcT4asnNixb0yybSElz5dkyFHVGlJ74/wu2igdiFC5q7Cnw7p6I/BLpEVgujVW+N/Tgbe7c7RvuLlLh/dulKcqcWBFPEO/3kQ5uqsME5chzlUQx9KgKuBP5px/NcLCKcp0fQDpvPAI4/AG4LclzrULi/NahAYDjyzjHmgXC4AndbGow6TfjngVbT7ryep9SEpW9S7vuD08BGXEjtUFSAVrzw/u/5h/Tg+reYi3vMxUsRqSbrB1wTUdqSC72afcYdZNogf44Uiu07OBxyKFgWyUNBoBYz8q2G5sEPeUIH1qn4O0E3q2/mzb/Y1KhHh8yLLVnqN/RlhXYzn1t8QoktNKzhoK9/t6NXKnpZwrUer/EjWYn1yRXMeq4apJyIfjVS8Zpj4SmdzSUFT0EtNGdqrpp+F5r0aKD4MEUZ5CeSPXDaTg3ysK2kORqYt1FxDVMiKtX0t5z8s4WT9Hcprbbbb9gMO6jDDVkCqMl+hB10C8picw3BZEWZO5roAwiYfYNulO4MeetzMQzEWi7z/X8T4BOKZDdfFhFsk6BumLWqTlSFjL59FsZ+bOFUeEMIF+DZyNdBU4A/gF8BvgywjzIBlQi5t+YzqwYwkM4bCX91Yd4g867t/TOfiN/v7pJjpUG4GI/KKMszUakl50KcJiSwrul8ONwjtW4vF+HNIybEaHvRvW1+bAC93x3hfcikRQi4xtcEY8HnFMDltmTUOCBEv0Pi6lWBEwRrRg1lmIQ20a8O9ItLVMjqSw5mYAb0VyvBsFqkWH9JELkTzhWi3jn/6I0ANqJSy0ERL1/9jGoIpN4Z3xgsne4XC+AfiMiTaPI0WHtigRvSvcwx0FStkP02N9Cx65Y4AU6enAN3X9z0FoYnNKRHMJgnUe8BETqStKtboMz+txyHoYQ6r7n63K/RZ6WM7UdbYr0u7uV8B/miKLVTbIFiH5bWl67m1GOUgGoDzFCMXwd8DLEObUDHPtgLT7+ynwFTVS4opH6hJjQNpn2DBgp3NIe1kH/K9Z00lOfWqa7psy59LP1HW1fc7gRmIqY2/u4rHn+twaxLmYFLQTEp3LNyEO+2GwQ4IhdbDKpET3zm+86wQzkajwT4yT7NklPCdjxOF9XJf3toxmvaKklkEJvh8JGUclVO4jpEr0VW2EfPAUPqoL4y+Mx//qYhjTg2Jb4Kk08wqiEgomckYKBx05Cw6VH+raqrmwGciamIY4tEKE4CjgXSWJyEdmXbxb92pcMBpcU2X/ZyNGtXR071Q5Ttd4ZFhNWdc04FTgs8CWFTfIXqDPkKSiM7cOKMIXxvog4KtIHY12Y58AL0f6Hx9qfhdVLGqSINWJj8kY5+toOueSAeY7RqrMF4kKB4phMAomSiZLw5p+jO7vovTHBZQndYARKqgUI2mUUZe6/JOBVw1B9obPmYGkOi7U3/1O9YmpXmBtXJ0cZyNpjOPAh4G9TNvaMsiDnZHgTjdpDwnwN5XTERDXWhxq56jRMlYioyXJUXApMl6NJQUV5PD+q/WQtoN7gC6EeAhtETrd78wOcxRoANNpVlarDdh5cR9S3MIPo8H3hPueWQNvRbxow/buBSP4eUjOV9Ll2r+QZv9gp7654+etCI0rMZGtrCtEMV6tZ92RKap02WVUuL/tkfyoJDUODzKYdIEwlrPViFpoZEvU5moATwC+Drw0RXWNKiBXY11n/21yaxOjL12jBuUwKLnrgY8XGMfwf3MQGuTCEjn7wz3M0nVeJK80jPsqU/zHz4je6p43IimKReyEyHx9r+ojjQHpIzaH/B1ImkYoDvxrpIrw9Ck+t3VgE3UMXKC/2xL4BMKsaAxRdwyfOx9hdB3YpRM1osmcidoZRFfQTBovy8armUJZEx0E2yxjCBcdpB8i0WBbiOuxeliXMZL5KKTIUCclYgdVPhiwVycB/qTKwZj3tRx4gbLfICyKmiptn0O8/8Ny6oR0hQOA03SvFnVY1RCv5beNl9KVHKZ0gazdkfzUPHm/kZFFhwHfBf5LFe245AyDcZMfdQpShMo6sSMktedyBlcXYpGeLXnTLsZMBdkvIrnDO5pI8niJi/oF2foudaCkn3ktzZZKY0OS+z8DvmHWRN752B+J0lGiyGOCFD19ThepMyBRPk+d6c86uxL4fYGWXWmDZh7wKaTgUaPP+946Qd+i8r6un3mb6kk11yP+b342IAHBhmkb+99qhMZDorOH+XkxUvem6NkW/v8SpH7O//2u1mKB34t4a8tEk4kQHv/fcxwyM7rcUA3gkylBOh3pqUUJCw3FSB/hg1u0p7Cb/+WqsAwyRzQ0LH+ffq5TohlKUYufmnyw7XRv72EOgkEqNuEePq3OmaLrMTaFLX7pVHs3hNm4b27UBcVvK5VRP6FZSCs2h2+Z+iLXkejdl5FoapJxhl9Mk9GVDGDst0bSh4qMVc0Y9C9AqHivMTKibMVZrJz5D6R3rZVdsZG3l3RhHNBjJtYnkGhdXvkYnvHViJMyKUHxtTrCevgQTeZbVCBnuo5E+mJnovXFEI6Rll0TxkFXNKViKdIB5tFm39f65MCKEdbQ6anI9O+RANtM1yU2SlX5EVKDJdhaxyNR/GkDNoYjo7++CgmgzOgi0Bme61SEORPl8dYsQQoxxTlyfvp91fXrLYjnv5VRGh5sV8QrnuS89/D+vzU5AvaQv7vAew3yaujXy9SwaYVn6KE4yHsLY/ULp0RPSsncGSnxnmf9hfWwAqmwGbAHUrU7QVpohTWz34AKqVm2woHARV3uJyuLjithldNpapzbuWh3TejXM4xDIirJc4AUDEwQ73De/f6hAT9Hzci4iUnIqnAGrEFyh3ducRhHQ8h9tp+5l1ljdj/EpujL0QPMDwbYRw3vbs9Iu1d+iERayzj281WJWpfxrKFX8gfYuK3SMM+Od6i8r+ecl9jMwbQhOiPC584FvpCSlUXW03lI1JES0Dk3R/ISrb6ZZy7eVVL9yaZnXFvgzGv1nDciUf+sdTCZNYRJITzZrKPY6EOh/s9shDGX91nC/3w0ZVhTgiAZSKpDI6dctnt/kQkCnpRxRn4mZYhGA3gW1Em3rstzJsz7X1Um5HK4hIf7eEkMwDABFyI5LJ0M4R0LGsJB0TspQ3HfscBBMowr3Nf1wLOQap2z9SDbUb3Xdw14HoOCtl6VspobwkMzhKfre52WIdDu0MOnZhTnWo+F2Jj5/hikQEFeZaDVWv9JSdeUG8KDN4TD5+ymSk3cg3Mm0fPjI2qUzeaRkeSxPjxjOJyzKIJ7IZS+m1vsn9g4cwdVHCi8/2ZI+stknOaNlPz6JlJQZ96Axz5LBm6CUPEuyhhve96tQtguw45mh8/fCol2FZG34VneaMY7GtLZ90ZVfBtdOlZeUAIm36gbwtMRdlcvAjoPqeNjr4zPGjd7M12DoGb27ljGWfZYJLrZMOs7Nl1yNjcplW4INw1hkNTLm/XvDaOzfBNh9NEnp2stlRN8mq6PbuyYcLaso2AAJTKRpDVdenr6YQj/WQ+lTobwduphKrIAViO5KGnhv1tJo8FZG3ItQsv6PpIMfmWLg3tQ83WOmS83hIdnCIe9fIc5DIJAC8VVlqQOj8kYmjVjTAVF+cM0o0YTk3CuPAA8saRryg3hwRvCmHX+hx7IujilqK5EaMgvptk+z+7R6Tpe40YRq3UoGGUVt3F9/bSMZ9oUyWH+bzXM4zaKdLjvZw9h/COEituLsbey4UEk3/X1NNOT0uu0F2M/PUMxmo3kzP4/1TsaGVH4tNx9bwmV4YOQVLe8TopwPtxPszXUoNNnUAf6si7WVMMo6tNLMBejagjbgNFhamRMxhGWdkJ+HklTmdvlvW2qr/+Grv8sBs0GhO6LSal0Q7hpCIf5PcXMUWze8wokSjvb7N3xSTgCowxnxpHmXO/2fAlr6+d6r4XuL/zjqZOI4PTasDrLDFLU5p63MkZgnPO9L0ZoHulw/74VMIQ7bdx4wBHqoJS91I3goRvCNsLxijZr5mLTPL0VRTDqoGCmBcwmSDXZv/VgLYZ7/YSpAeCGsBvC9rNeoI7bXjB4Ghk/X6Zj8vwWhlmn3u1RDmN+KfAvwHuQ/MbVOeR8eNZfmv076Ij8/uqkavRg7LMU6jvVIXAiQsWe0eOxRxXAo4B3qgG+ooWRmDUfVyJ56pQstxldT0kBQyXoRNch+cKDeqYxE8i4sgu909739iWZi1E2hC2+2CNHmH39aoTh8h6V7YchUcj5KQbHJuqkPFD/73Qd6w0t3jvs2fNTPabdEM42hBer0WvXrnUonEWzI02aYZNXd0wHNndBGFlrCsquVmvqQV0/mUHU8RytEf4beK4q5MPuI5U3SrUSySfek87N10OC/31ILjCptgcPVqjSW1Yl7UEbDKFq659NZbZhtJFw8IgCU99TD96jU8UOElV4DlAP6TkqEG8zldOL9LPeBmmL8EJjkE+mX2CQO9foQfWwrylHxtr7GVLp8t9Mm4eoB7lJQabtq9cbgNvVeXQzUiDpZj0rVunfaghDZ50pJJOoEjdblbd5CBNjsZ6vO+vPe7R4vqy8prCPVwEfVONtkHsjFCD5pzoJ3t2icGM3Bpx99m2A1+r3dyOV8G8BbkLSglaq0nSbYbqsMTpOrGM/S8d+ro77YlWuF+q475vSF+KUwpZVWGa1Km13lVAu1RBa6Dt1feTp2xyKrO2CMMv+Rce4n88WWuptAXxFdbekgL4Z9vu9iAP+Vi+kONC+rqcCz0Rq6iSTiAjaPT8XYX8FBtg63d/LdL+HfbmJOm93SRm2adlJqk3QFxDmg+sS7YvO3a5y/dumXVxkZMlzkVZUZ6re+DtjwBZtBbsn0lbzeJodESZTuC+c3V9D8oMzK+mPd1CeazoIX0GojdGQqgkmpjVBo02Z8/C7DSoIkxyTUTOHa5yh1EclaSTdjRIxrGqCdT1Al/thVCqsRdoGfE+VwsQcJoHy8li93oh4TP+uXx9SZ1HDKIehBc18VeKXIq0QDjf5I/UWHr+igmy1CuMbfE05Wsi9B5FowD5IdKBXVdFtZeDYeMkXm/95SM+d9bpWIyTiP5GSydP1nmaqUjGfR0Y3G+b8bWfM27P4Q8C5Q2wBUkfyuHZFIuaNHuXxW+U4RDcWsXEe23p1jm0wjuu6/pw19jPM2M/M+MwJM/a1Ds88DXEc/qCEUbvEGLYfUsPi5JzKZTgT9kBoqq9G0s3GzTzQw0hwA2HyfRypJVFE5wrBjoeAt+l55a0aBxv4uEWN4U/3YO/bPW+7jcxGiuXu3mFP0oKhFvb2NN2v3/KWSbkcTOPAj1WnP9HsTdsXfibwEjVgr0fqOf1cHRdr1HFRy+gzvy1Sy2gnJKq8D806UBOTbKkVzv9fIsyKrh0eNXOzV06iMlyvqNHfz0EhDAfXy3PkI9pQ+3syQvYghUeurQg9uiz07D9OMlfA0VtqtGUGjJviFhMZ71nP2OMT6ij6O5Kv8X2k3ckFqnRclbHP4h6lU4R7+c8KrCmnRg8vR9iu9cfrYZxMopJ0p2cNhUM29IiGvUHfrwitu25a5TDkAnI1Q2s9uw2VuFfnTBj7Rg/mcoNeRcZ+wlQm3r7kvafDvW2qzoq4C5r0uUi0vNcFtILc2xbp512UDm3z5t/dg/oWTo2eXIX1z7fRLXohd+vGwThhZGY9hywIf78aqf2T3rNz1KlVlBp9+ohSo9PPtARJD8p6vzhDTwgFc6/Stf9T1R1/rbrkBTTzt1sVTpys3ng5whSYlHy2Sud/DLGVUhAcZ5uH6WQI70wzKtzoMPkTNCtGpw3h6fq58ZDzpKtwBQXx8Z4bXDpD2K7thcCvOuyNxiRyMnqlAId7+5Qp+lXmNeWG8HANYSv/d0EqGffTIEvnIcVm/ee54i7PVFuw5AxTrCQqiczaFClWNKgaFYMce7u3LzZttqIKMcXeX3Bu6qYzxfNapA90W6UbJML3py4CLQ3z9e1011vUDeHerq/NjW5RL2F3lYdptperZdRo+HYXhvAnRtwQtt8/B0nDaSU740nqjr3UG+/P20qwViDv76tI3ucw+fSb5jj0A1XjJvXWkoMi87BObpRBO9uARDg9j4COFIoI+GQJ1skoGsT0kCq3DKG43NGGZlzL2A/trqwiCZO5z0Ch+SESDd5QkTVVq1g6AyOYD19Tpf3ZwNfNekz6tH5aFf/odHXTHzc2n/FV4M1I7lwZ9kY4M1cg+bwnmX0b9/H+BjX2idEv/qrr64aK0CsTMz7vRSpxP5xzX4zp/O2sjpf3qy4WF+zzHGXQXo9BKJSPN5TaIufDOuA1SI72Btc7hr6+7kdo9P80ueZJSWqkNBDWwG9b5IpuQAr+JQWeN0ZSAJMRWntRm+f9IVJrwKYL0UH/K6I7Rj06/9cgaYC/NfUHJqW02QX+yRYFmQaFLTKS4VsleMdISD7Pc3aagMvUaBjz3MS2i+9qJHrnin3v8GCPDejE5P4fjxSgquVwFnWq/NfLtRT27A+QFIeHKqJsNtTJUFSxvt84ksp0EG4oKO+TkjxDkEcPAK9UpX+5Wat1qqlohueqI7mU/67rrUx7IzGFwj4GPA1p6VczymhSYUdvhES8XoTkv1VJJ7CRl/9GimBdlMr1a6crxghz5V1IL/dnIgXfkpSTwLazGjM/W8V3RzWoz0LqSdRz5gQ3jLJ9NVKQ8cttioWWjT48VfKFn4cUTcqztuhz7YKaYZad1sFgXV5gniKa1N8ypkZ044SIjc6ZtLCtPqF7NyqZ7hgcaQ+qEfzFXp+NtlT5l4dAewifdTPNRPlaDmrfi1M0qFZ0gIeQ4kDpyYlMo+2zS0j3KAvlJIzjGz3C1XPMRfJw4wLU6Jto5kW0Ui7C7w9FvLf9yqfshtIygeQxb9anZu39xH/xyH6ora4Npj5BmZ4zyM+3pWi4eebuxBJSxEAiTv+jBlrSo/zSQe6LhmkNc2KP6Kn9Vvxrxuj5KFJsL6nYOWrX/zKk+vLmQ+iv26+52UkNhHrO3M44lZf7S3U07aR6Uqf9uCfSm/minK0fs3IQ1yIFXPcoQW58Xhm0AGEoFqFGx8A7KqhT1Uwb08/QrCA8McDUSrteluu+nZOj9epjTQu+RgeZXFd5vFvJzu9wH89AmK550+pilQXTcgZYTkEYGcmQz1Krb92I0Lf73rpoW6M41wfM728glcmiDgpAOKCeZzZD3KFY1jtbeO5qphffmgKK4VQzhM8BtqxA0ZAqIm8v7/D3n+TIpbcCcw+kgEHSox6sk3F2rQZel/P+y3j4H51zrkLNgbUIxbJMinVYF482B2kjZ8GnPUvYSzUyVUefjxT+SQaUP9yL4jDh5y+lWitVYW/Ye3wi8B2jtNSHWHek6NifCxxp9vkonHE1UyTohepwzbsv0n+7AulG8FaE7nw4sJ86Wp+K0OS/oYZDkZzAtL51KXBcB6OmrIWkfl7ASRrG5RkVDS7UTBDpuUg+fXptxX12XCXAX4Cn5NAngk0xW41Ba7i3qgGRIKycsual76hBkTz1jcLz/FuO57F/e61xcNaHHIj7o8qdvjMwwgAfg+QBDVKJCIP8yRwPGoomnJQj0hUWwBdbbJawQaYhdKLEDeFHCOt7gUd5NLhv++2AlLBptBHMDT14iiprm9Os+DgIIyGrqMLFbFxorUprKdzvHIQSZqOOWQdpkEl/UHkVlUy5Ds/z9Yz5Sl/B2fjNSbY7GJRBtgDpNXpDm+hrPOToo73+rsr/9IoaYXYvjwFPQnK3+llor1djvxxhOi0Y0Zz+KHUGnESzOGOeecn6/XrVD+/U8VtfoChOq896AGHObFPB8yFE2D5SMOp+L1Kpt6prLjJO1a2RgrvL2zxvo80Z064gYdZYrgE+QDM4U2QvbIbkwnaSGaciqQFlXIuhsvvHW5xtdhyDbXUV2YWyOrFKjkBS7AYlx7Pkx//oGhuIjA4PPx3h2g/SKAyfcwPSa6oVFWFM73EuzSjXRI7KrT9LtZrJ2iDbIoWgkpzl2qdCu6TYVNz2SHD/onMvRIqbdJqTD3RB0bFRjuOAf2TskXoPK/ql9+NK4H1I65Vet+cYhuPisUgOdqexuI1mde9aSRXk/VsYjOnrcsoXDW53eINQ916CRMIebkG3qg/AGTSRcZZsAH6P5PEvqAAVuihVfS6SY3oOQjlOWsicRp/Pr4kWrd+uQWipO7QpIDhKxrBlo2yPUNlvyhibrHmxCnWjjZ6Vtc7jNvPQUKP8VGMQVi1Vxq777VXmt0rNsO2BQk7rGKOjw6Bn/KsRmvjyHu/ntUir05NppoYV1SfC/81E6kv8RedshcqpKxHmw7Mq4uCaB/wix9jdDTy54BkTpWyjT5hiY3bfN3oYDE1Hnf8KHGvkV23QA7w90gdqkP11w4B+D9jEeNtCUQbLbX9zTvpN3XDLd2szmOG5d1AFJalgrlk/5uKrJY4CjZrH/ilITtatKpjXIFTie9RB8zoV4JNVUndQ7+0FJr/H0l+LGge276c99G9C6J6HVljJaTVfR6kj7o4UxaquB+oPjBFc9r2zP9JW4i6arRNC5Gc58CPgwAoZarXUOpuPRCk/gVA8726RbzZZw9gqulnnxiqkANCnda9v0qUyV5UoUcDjkErGv9Gxn8hwCkyk2DDdOh3q5v3s3x9Uufod4A3A4jYOFEaYgWSfcyFwAnCmOvbWZehOdl4abdpYpSNQEy3asj2o58L3EZrmdiMyDzXTfubOlKGwIaMf+e+AvUeIgZBeW9OBg9Uo/iqSenC97v/7VK9Zn6HDr9M1slzP1qsQdsn7EBr5tj1YL2lG6FIk6rkfjyzWW/b+ziB073fqWN2jY7tGdchbgW8Bh3V5fqfH+ADgczqX9QwZXkR+WydZPXVOnge8CaleTy/6BHf7ukSVvbMHTA8IlUnPAd6CFNAipdS8HGm5sjDnc4ZqYy9QI3usRSW08NxbqdfphNTGSKZIa5SGjtGl6o25w9sWDAwLVNgvRaqor9OD9Vqk+nAvDqzQbmAz3ePPQ1pnHNihxVoeGbNcvazn6WH/j1S14VFaQ5sAuwIHqVwKfQwv1L2zvmLrbhd1Fm6tzq9larhdoYdrVZ0Wifl5W1W+j9J521EVILpY+3nOgtuQ6OO1SI7TP1WJaHWPo+bgS1LtEXdBGBWHIDTY3cw53uuxX44wGW5Rp9XluqYfGPGxz6vfYfI8d9H98AQ9e3ZpMS9Z8xN1qFJ7I5I7fD2SHnOR/m5iROfhcMTRfLDqklavukIdQp9SvYopsO9rOg5z1JbYTPXqhfq7hvm/FWooP6D6zjqEUfZAj2Vmp/eoir5r73OxXtshAZPlKvvuMu1jkx7JjL1VVjxOjextupDfabnxd5UPv1XHybJezUU0SbpDjBRHON0Yk4M0hq9HPIeXItHgvZD85f0LRpbqqth9HaFDNDoYtuH3+yAevuPZuIhJWduK0MOebCv1uX/bpheto78KSisjttefU9NDaX+kavsRCA1255zr+h9ILuxlqmxennI0jeL6yfNMVXnuKKfDI6n4fCUZ636Ryvatdb3vq4f8zl18xjWIV/5m3RP3qSJyG0LrS1PO4ilWCyFO6RebI+yUpSp3FiPOuF1MsaS8WKby5xok4nirjvv1GU6cWkn6n5bRaEENlaU6H7vpHG2v17ZszGTARITu0nG/1TiAluvP9/DIVoGjOA9BTs7WNb296q4hRehqYwCPenAhb/udIjTdfqyXKDUXieuOuWXGLKSi/P6IQ/kxKr+3yPFeK5CAybkqK/6ucqLn8iHqwSJOkFL2/6bCbjqDjUqCeA7TeS5Fjc9A9dkH8c63W/DpCVigwn9L9bYsQbx9RxhqzygYw5a28GakeNgwe8RNVeUkylhTvT4AbAuxOKMY3WwVcpsi3r5ZaiyPI57atTSLpaxFPI5Zyu8oK5xRi6hjZOhBVXuWJPW1is+Sd76ynmm6GmFzdM3PUWN5th7uochNKNiyRhX8NboP1pn+zEU/e6rItqSNE3qejvsMPXfD2G+pf1+m5/g6NXAf1GuDjv9DPvZ92RczdU5mZKRKxcYYXo+wYhptgivRFDgXkhzjHU/B9ZU2OKM2QaUopZM6yJ3+1m/dMb3/MbUhZunXhYizc77K8ocR5/BaxGl2v8ruh1u8d1y2gd3atKRoDKFYUzoHK55EzuvpBaqmdcrb2gEpOrFhwLnU/c4L/qxxOnhu8NQ4qGqmEB2TYJHUpuiaiUbouaMpMIdRat33Okd3LLUfXI62H/+oDzniPvbdnwWTnZcoYw9M1TN1bIqPRZ7WU75Pq7/OJ1tXotR7IzI04UuH1F6olz3J1tF99bRWm/Zk9XI0KmwMh+Ii55i8aBdMfkDlvRyOqbr2fS+UZ/wdw58Xh8PhcmLk5IXtJ3XzEJsr9yrieT7NIga1HvTyqgE/rXAP4g0Z4+IHmsPhcDgcDofD4ZjyCFTZ45Gk/6oafcGA/3LKkJ2sk+B4JD+pahTpYARfRLM3m/cLdjgcDofD4XA4HI6UwfgypDhOFfNibb+7/zKRz9okqQCHGAdBXLEI+Q1IyX83gh0Oh8PhcDgcDoejTWL0a5Hy11U1hkN0+N1IJUS6TNYOr3kKkidclfEIkfFr1Ij3Ig4Oh8PhcDgcDofDkcMAfC3NKGi9wpHhXyA9sOii+m2gjL+mQg6BUBjraqQNlOcEOxwOh8PhcDgcDgf5adInGsOqqsZwgvRDfTnSNzKrrHctVemsZozgGUhj6CqMQZira5FIMJMsfe5wOBwOh8PhcDgcU9IYfhVwR0ULaKVbM/0ceAmwU85x2Az4Sh/aPPUzJ/g6mpFgzwl2OBwOh8PhcDgcDrqrmnwMzdZKVawmHbNxNPdK4NPAC9QoXgTMRaK/84FdgReq4Vz2vGD7bH8F9nU6tMPhcDgcDofD4WCEo7aDMoZj4EjgdOAghII7XkFjq5GKdq9HaNP3IZWyVwJbIJHgndQwTkr8nLF5lu8AbwduN3PmcDgcDofD4XA4HI5JRoaXAD8zkeEqR4fjAnTjMleGXg98hGYusOcEOxwOh8PhcDgcDge9jUDPBL5YEWMxbw5xq6vs+cDLgP9nHBWeE+xwOBwOh8PhcDgcfaRjvwG4pSKFpEblsk6H84FneI9gh8PhcDgcDofD4RhsRenHAudm0HX96l9rpASpZL0rzSiwG8IOh8PhcDgcDofDMUBjeB5wClJoKimQf+tX/ihwcDDcB/y7GfvIjWCHw+FwOBwOh8PhGB5V+unA30Ykd7iMVOifA4cNoWq4w+FwOBwOh8PhcDjaRIeXAh8AbnWDeFIFvOyYXQG8HilSBtK2yuFwOBwOh8PhcDgclKfFEsATgTOBDTTp0p4/nK8lUqCV34/0bd7XjKu3RnI4HA6Hw+FwOBwOykuVngM8l42LaU14/nDHPOAY6dV8VMrJ4FRoh8PhcDgcDofD4aiIQTwLeCtwNdn9e6cyBTr9/BcCL0iNoxvADofD4XA4HA6Hw1EhWCrvTsBpwFUZdODGFIv+WgN4HfAH4C3Awoy8a4fD4XA4HA6Hw+FwUL3o8DTz887Aa4HfA6uNQfjwCOcRxwgtfIP53VrgLOBYYAszPuMeBXY4HA6Hw+FwOBwORq6YFkj0MxTVui0VIR6VXsQxj4x4X4MUwToG2KRF9W2Hw+FwOBwOh8PhcDCa+cMBjwLezcZ9iJMK5RTHOe7xV0iu9NKM8fAIsMPhcDgcDofD4XB0aVBW8f4jNR4BtgQeCxyJRIv3znhdyLOtDdmItAZvVm/fVcD1wG+BnwOXIVRw9P8T8x4Oh8PhcDgcDofD4ZgChnCaEhwhNOKArYEDgf2Bo4HdgdnAvNTrJ9SYrPXROE5Shm+UYfyuUUP3r8AFwPnAtcByNs7/jY3h73A4HA6Hw+FwOByOKWgIk5FHnDYUFwCLgB2BJwD7AtsBOwDTM96n0WacohaGbrufxzJecz9wA7ASKfx1JXALcC9wX8ZzJR79dTgcDofD4XA4HA43hPM8X9KiLdMSpCXTEmAr4CA1lJcAm/X4XlYjPX5vB27W6zok4ruyw9y48etwOBwOh8PhcDgcbgh39axRKj83jVlIFeYFSDuiuWoUL9TfbaLvscgYp4ka1Q8g7YwmgGXACoTqvFx/XolEetewcbTZUrvte7rx63A4HA6Hw+FwOBx9wP8HMm0YK43cwXQAAAAASUVORK5CYII="

st.set_page_config(page_title="D2C Sales Dashboard", layout="wide",
                   initial_sidebar_state="expanded", page_icon="📊")

# ---------- Theme / styling ----------
st.markdown('''
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
:root{
  --bg:#f7f8fa; --panel:#ffffff; --line:#ebedf2;
  --ink:#0f1115; --ink2:#5a6070; --muted:#9aa0ad;
  --indigo:#6366f1; --indigo2:#8b5cf6; --ink900:#0f1115; --up:#0f9d6b; --down:#c2453b;
}
html, body, [class*="css"], .stApp{ font-family:'Inter',sans-serif; font-variant-numeric:tabular-nums; }
.stApp{ background:var(--bg); color:var(--ink); }
.block-container{ padding-top:2.2rem; }
h1{ font-family:'Inter',sans-serif !important; font-weight:800 !important; letter-spacing:-.8px;
    font-size:2.0rem !important; color:var(--ink) !important; }
h2,h3{ font-family:'Inter',sans-serif !important; font-weight:700 !important; color:var(--ink) !important; letter-spacing:-.2px; }

section[data-testid="stSidebar"]{ background:#fff; border-right:1px solid var(--line); }
section[data-testid="stSidebar"] h1{ font-size:1.05rem !important; color:var(--ink) !important; font-weight:700 !important; }
section[data-testid="stSidebar"] .stMarkdown strong{ color:var(--indigo); }

/* Tabs -> pill nav */
div[data-baseweb="tab-list"]{ gap:4px; background:#fff; border:1px solid var(--line);
  border-radius:13px; padding:5px; box-shadow:0 1px 2px rgba(16,17,21,.04); }
button[data-baseweb="tab"]{ font-weight:600; color:var(--ink2); font-size:.92rem; border-radius:9px; padding:8px 14px; }
button[data-baseweb="tab"][aria-selected="true"]{ color:#fff !important; background:var(--indigo); box-shadow:0 5px 14px rgba(99,102,241,.34); }
div[data-baseweb="tab-highlight"], div[data-baseweb="tab-border"]{ display:none !important; }

/* Hero / KPI cards */
.bc-hero{ background:var(--panel); border:1px solid var(--line); border-radius:16px; padding:20px 24px;
  box-shadow:0 1px 2px rgba(16,17,21,.04),0 12px 28px rgba(16,17,21,.05); display:flex; align-items:stretch; }
.bc-hero .lead{ flex:1.1; display:flex; flex-direction:column; justify-content:center; gap:8px; padding-right:24px; }
.bc-hero .rule{ width:1px; background:#eef0f4; }
.bc-hero .trio{ flex:1.45; display:flex; }
.bc-hero .stat{ flex:1; padding:0 22px; display:flex; flex-direction:column; gap:6px; justify-content:center; }
.bc-hero .stat + .stat{ border-left:1px solid #eef0f4; }
.bc-lab{ font:600 11px Inter; letter-spacing:1.1px; text-transform:uppercase; color:var(--muted); }
.bc-big{ font:800 40px/1 Inter; letter-spacing:-1.4px; color:var(--ink); }
.bc-mid{ font:800 24px/1 Inter; letter-spacing:-.5px; color:var(--ink); }
.bc-sub{ font:500 12.5px Inter; color:var(--muted); }
.bc-up{ display:inline-flex; align-items:center; gap:4px; font:700 12px Inter; color:var(--up); background:rgba(16,185,129,.10); padding:4px 9px; border-radius:20px; }
.bc-down{ display:inline-flex; align-items:center; gap:4px; font:700 12px Inter; color:var(--down); background:rgba(239,68,68,.10); padding:4px 9px; border-radius:20px; }

/* Insight strip */
.bc-insight{ display:flex; gap:14px; align-items:center; background:linear-gradient(90deg,#eef0fe,#f5f3fe);
  border:1px solid #e3e3fb; border-radius:14px; padding:14px 18px; font:500 14px/1.55 Inter; color:#2b2f3a; margin-bottom:14px; animation:bcFade .5s ease both; }
.bc-insight b{ color:#0f1115; }
.bc-insight .ic{ flex:none; display:inline-flex; align-items:center; justify-content:center; width:36px; height:36px; border-radius:11px; background:#6366f1; color:#fff; font-size:18px; box-shadow:0 6px 16px rgba(99,102,241,.34); }

/* Pacing-to-target ring */
.bc-ring{ flex:none; width:182px; display:flex; flex-direction:column; align-items:center; justify-content:center; gap:8px; padding:0 8px; border-left:1px solid #eef0f4; }
.bc-ring .wrap{ position:relative; width:118px; height:118px; }
.bc-ring .wrap .ctr{ position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center; }
.bc-ring circle.fg{ animation:bcRing 1.3s cubic-bezier(.22,.61,.36,1) both; }
@keyframes bcFade{ from{ opacity:0; transform:translateY(10px);} to{ opacity:1; transform:none; } }
@keyframes bcRing{ from{ stroke-dashoffset:327; } }
div[data-testid="stPlotlyChart"]{ transition:box-shadow .18s ease; border-radius:14px; }
div[data-testid="stPlotlyChart"]:hover{ box-shadow:0 6px 20px rgba(16,17,21,.08); }

/* Inputs / tags / buttons / chat / dataframe */
.stMultiSelect div[data-baseweb="select"]>div, .stDateInput input, .stTextInput input{ background:#fff; border-color:var(--line); border-radius:10px; }
div[data-baseweb="tag"]{ background:var(--indigo) !important; border-radius:7px; border:none; color:#fff; }
.stButton>button{ border-radius:10px; border:1px solid var(--line); font-weight:600; color:var(--ink); background:#fff; }
.stButton>button:hover{ border-color:var(--indigo); color:var(--indigo); }
.stDownloadButton>button, .stFormSubmitButton>button{ background:var(--ink900); color:#fff !important; border:none; border-radius:10px; font-weight:600; }
div[data-testid="stChatMessage"]{ background:#fff; border:1px solid var(--line); border-radius:14px; }
.stCaption, div[data-testid="stCaptionContainer"]{ color:var(--muted) !important; }
hr{ border-color:var(--line); }
div[data-testid="stDataFrame"]{ border-radius:12px; overflow:hidden; border:1px solid var(--line); }
</style>
''', unsafe_allow_html=True)

# ---------- Plotly theme + chart helpers ----------
PLOT_BG="rgba(0,0,0,0)"
PALETTE=["#6366f1","#8b5cf6","#f43f5e","#0ea5e9","#14b8a6"]
CHANNEL_COLORS={"Shopify":"#6366f1","MP":"#8b5cf6","Retail":"#f43f5e","Cocoblue":"#0ea5e9","Myntra B2B":"#14b8a6"}
def style_fig(fig):
    fig.update_layout(paper_bgcolor=PLOT_BG, plot_bgcolor=PLOT_BG,
                      font=dict(color="#5a6070", family="Inter", size=12), colorway=PALETTE,
                      margin=dict(t=16,l=10,r=14,b=28),
                      legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(size=12), orientation="h", yanchor="bottom", y=1.02, x=0),
                      title=dict(font=dict(family="Inter", size=15, color="#0f1115")),
                      hoverlabel=dict(bgcolor="#ffffff", bordercolor="#ebedf2", font=dict(family="Inter", color="#1f2430")))
    fig.update_xaxes(showgrid=False, zeroline=False, linecolor="rgba(16,17,21,.13)")
    fig.update_yaxes(gridcolor="rgba(16,17,21,.06)", zeroline=False, linecolor="rgba(0,0,0,0)")
    fig.update_traces(selector=dict(type="scatter"), line=dict(width=2.6))
    return fig

def plot(fig, **kw):
    import streamlit as _st
    kw.setdefault("config", {"displayModeBar": False})
    return _st.plotly_chart(style_fig(fig), **kw)

# ---------- Indian number formatting ----------
def ind_group(v):
    """Indian comma grouping for full numbers: 64698803 -> '6,46,98,803'."""
    try: n=int(round(float(v)))
    except Exception: return v
    sign="-" if n<0 else ""; d=str(abs(n))
    if len(d)<=3: return sign+d
    head,tail=d[:-3],d[-3:]; parts=[]
    while len(head)>2: parts.insert(0,head[-2:]); head=head[:-2]
    if head: parts.insert(0,head)
    return sign+",".join(parts)+","+tail

def inr_abbr(v):
    """Compact Indian magnitude for chart labels: Cr / L / K (not Millions)."""
    try: v=float(v)
    except Exception: return ""
    a=abs(v); s="-" if v<0 else ""
    if a>=1e7: return f"{s}{a/1e7:.2f} Cr"
    if a>=1e5: return f"{s}{a/1e5:.2f} L"
    if a>=1e3: return f"{s}{a/1e3:.1f} K"
    return f"{s}{a:.0f}"

def inr_cr(v):
    """Compact rupee for the hero KPI: 5931802140 -> '₹593.2 Cr' (no truncation)."""
    try: v=float(v)
    except Exception: return "—"
    a=abs(v); s="-" if v<0 else ""
    if a>=1e7: return f"₹{s}{a/1e7:.1f} Cr"
    if a>=1e5: return f"₹{s}{a/1e5:.1f} L"
    return f"₹{s}{a:,.0f}"

# colour-name -> hex, keyword fallback so it works for ANY brand colour ("Bliss Black"->black, etc.)
_COLOR_KEYWORDS={"black":"#1c1c1f","navy":"#2c3c6b","blue":"#2f6fd0","brown":"#7c5430","taupe":"#b9a48c",
  "white":"#c3c8d2","cloud":"#c3c8d2","burgundy":"#7d2436","red":"#d6453b","mauve":"#b488c6","purple":"#6d4bd6",
  "pink":"#d98aa0","rouge":"#c45a72","grey":"#5b6470","gray":"#5b6470","green":"#3f6b5a","seaweed":"#3f6b5a",
  "olive":"#6b6b3f","beige":"#cbb89a","ash":"#8a7a6f","oyster":"#2b2b2e","herringbone":"#9aa0ad",
  "yellow":"#e0a83a","orange":"#d97a3a","lilac":"#b488c6","sand":"#cbb89a","teal":"#14b8a6"}
def colour_to_hex(name):
    low=str(name).lower()
    for kw,hexv in _COLOR_KEYWORDS.items():
        if kw in low: return hexv
    return "#6366f1"   # safe brand fallback for unknown names

def _pick_colour_col():
    """The colour attribute name from the master (or None) — mirrors the SKUs tab pattern."""
    cols=(CAT or [])+(LABEL or [])
    for c in cols:
        if c.lower().strip() in ("color","colour"): return c
    for c in cols:
        if "colour" in c.lower() or "color" in c.lower(): return c
    return None

# ---------- password ----------
def check_password():
    def entered():
        if st.session_state.get("pw","")==st.secrets.get("APP_PASSWORD",""):
            st.session_state["auth_ok"]=True; del st.session_state["pw"]
        else: st.session_state["auth_ok"]=False
    if st.session_state.get("auth_ok",False): return True
    st.text_input("Password", type="password", key="pw", on_change=entered)
    if st.session_state.get("auth_ok") is False: st.error("Incorrect password.")
    st.stop()
if st.secrets.get("APP_PASSWORD",""):
    check_password()

DRIVE_FILE_ID    = st.secrets.get("DRIVE_FILE_ID","")     # single online file (fallback / back-compat)
DRIVE_FOLDER_ID  = st.secrets.get("DRIVE_FOLDER_ID","")   # folder of sales files to union (online + retail)
MASTER_SHEET_ID  = st.secrets.get("MASTER_SHEET_ID","")
MASTER_SHEET_TAB = st.secrets.get("MASTER_SHEET_TAB","Master SKU")

# ---------- get sales file onto local disk (Drive download or local sample) ----------
@st.cache_data(ttl=3600, show_spinner="Loading sales data…")
def sales_file_path() -> str:
    if not DRIVE_FILE_ID:
        return SALES_LOCAL.as_posix()
    from google.oauth2 import service_account
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaIoBaseDownload
    info=dict(st.secrets["gcp_service_account"])
    creds=service_account.Credentials.from_service_account_info(
        info, scopes=["https://www.googleapis.com/auth/drive.readonly"])
    svc=build("drive","v3",credentials=creds)
    req=svc.files().get_media(fileId=DRIVE_FILE_ID)
    out=Path(tempfile.gettempdir())/"sales_data_file"
    with io.FileIO(out,"wb") as fh:
        dl=MediaIoBaseDownload(fh,req); done=False
        while not done: _,done=dl.next_chunk()
    return out.as_posix()

# ---------- load master (small) ----------
@st.cache_data(ttl=3600, show_spinner="Loading product master…")
def load_master() -> pd.DataFrame:
    if MASTER_SHEET_ID:
        try:
            import gspread
            from google.oauth2 import service_account
            info=dict(st.secrets["gcp_service_account"])
            creds=service_account.Credentials.from_service_account_info(
                info, scopes=["https://www.googleapis.com/auth/spreadsheets.readonly"])
            gc=gspread.authorize(creds)
            ws=gc.open_by_key(MASTER_SHEET_ID).worksheet(MASTER_SHEET_TAB)
            df=pd.DataFrame(ws.get_all_records())
        except Exception as e:
            st.session_state["_master_error"]=str(e)[:300]
            return pd.DataFrame()
    else:
        if not MASTER_LOCAL.exists(): return pd.DataFrame()
        df=pd.read_csv(MASTER_LOCAL)
    if df.empty: return df
    df.columns=[str(c).strip() for c in df.columns]
    key=None
    for c in df.columns:
        if c.lower().replace(" ","")=="sku_code": key=c; break
    if key is None:
        for c in df.columns:
            if "sku" in c.lower(): key=c; break
    if key is None: return pd.DataFrame()
    df=df.rename(columns={key:"sku_code"})
    df["sku_code"]=df["sku_code"].astype(str).str.strip()
    return df

SALES_COLS={"marketplaces","date","mon","yr","sku","product_code_planning","color_code",
            "qty","subtotal","reference_code","product_code","Qty","Subtotal"}

@st.cache_data(ttl=3600)
def classify(master: pd.DataFrame):
    cat,num,label=[],[],[]
    if master.empty: return cat,num,label
    SKIP={"product code","color code","category code","size code","style code","style no",
          "product code planning","sku_code","key","accounting sku","po product name"}
    NUMHINT={"asp","mrp","cogs","price","cost"}
    for c in master.columns:
        if c=="sku_code" or c in SALES_COLS: continue
        lc=c.lower().strip()
        if lc in SKIP or lc.endswith("code") or lc.endswith("sku code") or "asin" in lc: continue
        s=master[c]; nun=s.nunique(dropna=True)
        isn=pd.to_numeric(s,errors="coerce").notna().mean()>0.8
        if isn and any(h in lc for h in NUMHINT): num.append(c); continue
        if isn and nun>40: continue
        if 1<nun<=60: cat.append(c)
        else: label.append(c)
    return cat,num,label

# ---------- list ALL sales files in the Drive folder (online parquet + retail CSVs) ----------
@st.cache_data(ttl=3600, show_spinner="Loading sales data…")
def sales_files():
    """Return [(local_path, source_type)] for every sales file to union.
    Priority: DRIVE_FOLDER_ID (list+download all) > DRIVE_FILE_ID (single) > local sample.
    source_type is 'online' (parquet) or 'retail' (csv). The master Google Sheet is skipped."""
    def kind_for(p): return "retail" if p.lower().endswith(".csv") else "online"
    if not DRIVE_FOLDER_ID:                                  # back-compat: single file / local
        p = sales_file_path() if DRIVE_FILE_ID else SALES_LOCAL.as_posix()
        return [(p, kind_for(p))]
    from google.oauth2 import service_account
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaIoBaseDownload
    info=dict(st.secrets["gcp_service_account"])
    creds=service_account.Credentials.from_service_account_info(
        info, scopes=["https://www.googleapis.com/auth/drive.readonly"])
    svc=build("drive","v3",credentials=creds)
    items, token = [], None
    while True:                                              # list folder (paginated)
        resp=svc.files().list(
            q=f"'{DRIVE_FOLDER_ID}' in parents and trashed=false",
            fields="nextPageToken, files(id,name,mimeType)",
            pageSize=1000, pageToken=token,
            supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
        items+=resp.get("files",[]); token=resp.get("nextPageToken")
        if not token: break
    out=[]; tmp=Path(tempfile.gettempdir())
    for f in items:
        name=f.get("name","").lower(); mt=f.get("mimeType","")
        if mt.startswith("application/vnd.google-apps"): continue          # native Sheet (master) -> skip
        if name.endswith(".parquet") or "parquet" in mt:   kind="online"
        elif name.endswith(".csv") or mt in ("text/csv","application/csv"): kind="retail"
        else: continue                                                     # xlsx / other -> skip
        dst=tmp/f"sales_{f['id']}"                                         # distinct temp path per Drive id
        req=svc.files().get_media(fileId=f["id"])
        with io.FileIO(dst,"wb") as fh:
            dl=MediaIoBaseDownload(fh,req); done=False
            while not done: _,done=dl.next_chunk()
        out.append((dst.as_posix(), kind))
    if not out:                                              # empty/blocked folder -> local fallback
        p=SALES_LOCAL.as_posix(); return [(p, kind_for(p))]
    return out

def _canon_online(con, raw, tag):
    """Map an online sales file (parquet/csv) to the canonical 7 columns via fuzzy pick().
    If the file has no invoice/reference column, synthesise a unique one so that
    Orders = COUNT(DISTINCT reference_code) preserves the prior per-row count semantics."""
    low={r[0].lower():r[0] for r in con.execute("DESCRIBE "+raw).fetchall()}
    def pick(*cs):
        for x in cs:
            if x in low: return low[x]
        return None
    rev=pick("subtotal","revenue","sales","amount","gmv"); qty=pick("qty","quantity","units")
    sku=pick("sku","sku_code","product_code"); chan=pick("marketplaces","marketplace","channel","platform")
    dat=pick("date","order_date","txn_date")
    ref=pick("reference_code","invoice_id","billing_id","order_id","invoice","bill_id")
    sku_e =('CAST("'+sku+'" AS VARCHAR)')  if sku  else "''"
    rev_e =('CAST("'+rev+'" AS DOUBLE)')   if rev  else "0.0"
    qty_e =('CAST("'+qty+'" AS DOUBLE)')   if qty  else "0.0"
    chan_e=('CAST("'+chan+'" AS VARCHAR)') if chan else "'Unknown'"
    dat_e =('CAST("'+dat+'" AS DATE)')     if dat  else "CURRENT_DATE"
    ref_e =('CAST("'+ref+'" AS VARCHAR)')  if ref  else ("'on"+str(tag)+"_' || CAST(ROW_NUMBER() OVER () AS VARCHAR)")
    sql=("SELECT "+sku_e+" AS sku, "+rev_e+" AS subtotal, "+qty_e+" AS qty, "
         +chan_e+" AS marketplaces, "+dat_e+" AS date, "+ref_e+" AS reference_code, "
         "CAST(NULL AS VARCHAR) AS store FROM "+raw)
    return sql, (ref is not None)

def _canon_retail(con, raw, tag):
    """Map a messy POS retail CSV (read as all-VARCHAR) to the canonical 7 columns.
    Cleans Indian-formatted money/qty text, parses DD-Mon-YY dates, nets out SR/IR
    returns, forces channel 'Retail', and keeps the store as an attribute."""
    low={r[0].lower().strip():r[0] for r in con.execute("DESCRIBE "+raw).fetchall()}
    def pick(*cs):
        for x in cs:
            k=x.lower().strip()
            if k in low: return low[k]
        return None
    sku=pick("Product Code","sku","sku_code")
    ref=pick("Invoice No","invoice_no","reference_code","bill_no","invoice")
    dat=pick("Invoice Date","invoice_date","date","bill_date")
    qty=pick("Total Sales Qty","qty","quantity","units")
    val=pick("Nett Invoice Value","net invoice value","subtotal","net_amount","amount")
    typ=pick("Sales Transaction Type (IV/SR/IR)","sales transaction type","transaction type")
    sto=pick("Invoice Associate Short Name","Franchisee Name","Store Bucket","store","location")
    if not (sku and ref and dat and qty and val):
        raise RuntimeError("retail file missing required columns (Product Code / Invoice No / Invoice Date / Total Sales Qty / Nett Invoice Value)")
    # everything CAST to VARCHAR first, so this works whether the file is a CSV (all-text) or a typed Parquet
    def numexpr(col):                                        # " 1,599 "->1599 ; " - "->0 ; keep real negatives
        c="TRIM(CAST(\""+col+"\" AS VARCHAR))"
        return ("TRY_CAST(CASE WHEN regexp_full_match("+c+",'[-–— ]*') THEN '0' "
                "ELSE NULLIF(regexp_replace("+c+",'[, ]','','g'),'') END AS DOUBLE)")
    dv="NULLIF(TRIM(CAST(\""+dat+"\" AS VARCHAR)),'')"
    dexpr=("COALESCE(TRY_CAST(try_strptime("+dv+",'%d-%b-%y') AS DATE), TRY_CAST("+dv+" AS DATE), "
           "TRY_CAST(TRY_CAST("+dv+" AS TIMESTAMP) AS DATE))")   # try_strptime: NULL (not error) on mismatch; covers DD-Mon-YY, ISO, parquet datetime
    tsign=("CASE upper(trim(CAST(\""+typ+"\" AS VARCHAR))) WHEN 'SR' THEN -1.0 WHEN 'IR' THEN -1.0 ELSE 1.0 END") if typ else "1.0"
    store_e=("NULLIF(TRIM(CAST(\""+sto+"\" AS VARCHAR)),'')") if sto else "CAST(NULL AS VARCHAR)"
    skue="NULLIF(TRIM(CAST(\""+sku+"\" AS VARCHAR)),'')"
    refe="NULLIF(TRIM(CAST(\""+ref+"\" AS VARCHAR)),'')"
    # ABS(value) * type-sign: IV adds, SR/IR subtract -- correct whether the source stores returns as +ve or -ve
    sql=("SELECT "+skue+" AS sku, "
         "ABS(COALESCE("+numexpr(val)+",0))*("+tsign+") AS subtotal, "
         "ABS(COALESCE("+numexpr(qty)+",0))*("+tsign+") AS qty, "
         "'Retail' AS marketplaces, "
         +dexpr+" AS date, "
         +refe+" AS reference_code, "
         +store_e+" AS store "
         "FROM "+raw+" "
         "WHERE "+skue+" IS NOT NULL AND "+refe+" IS NOT NULL AND "+dexpr+" IS NOT NULL")
    return sql, True

# ---------- build a DuckDB connection that reads sales from disk + registers small master ----------
@st.cache_resource(show_spinner="Preparing database…")
def build_everything():
    """ONE source of truth: open connection, build sales view, join master, create joined view.
    Returns (con, CAT, NUM, LABEL, MATCH, HAS_REF). Cached as a resource so the connection
    and all its views are created together and stay in sync."""
    files=sales_files()
    con=duckdb.connect(":memory:")
    online,retail,skipped=[],[],[]
    for i,(path,kind) in enumerate(files):
        raw=f"src_raw_{i}"
        try:
            if path.lower().endswith(".csv"):
                con.execute(f"CREATE VIEW {raw} AS SELECT * FROM read_csv_auto('{path}', header=true, all_varchar=true, ignore_errors=true)")
            else:
                con.execute(f"CREATE VIEW {raw} AS SELECT * FROM read_parquet('{path}')")
            # classify by COLUMNS (works for csv or parquet) -> retail if it carries the POS-export signature
            cols={str(r[0]).lower().strip() for r in con.execute("DESCRIBE "+raw).fetchall()}
            is_retail=bool({"invoice no","sales transaction type (iv/sr/ir)","nett invoice value"} & cols)
            (retail if is_retail else online).append(
                (_canon_retail if is_retail else _canon_online)(con, raw, i)[0])
        except Exception as e:
            skipped.append((path, str(e)[:200]))
    if skipped: st.session_state["_skipped_files"]=skipped

    # canonical online rows + retail rows
    parts=[f"SELECT * FROM ({s})" for s in online]
    if len(retail)==1:
        parts.append(f"SELECT * FROM ({retail[0]})")         # single file: no overlap possible -> skip the heavy de-dup window
    elif retail:                                             # multiple retail files: de-dup by invoice+sku so re-uploaded periods don't double-count
        runion=" UNION ALL ".join(f"SELECT * FROM ({s})" for s in retail)
        parts.append("SELECT sku,subtotal,qty,marketplaces,date,reference_code,store FROM ("
                     "SELECT *, ROW_NUMBER() OVER (PARTITION BY reference_code, sku ORDER BY date DESC) AS _rn "
                     f"FROM ({runion})) WHERE _rn=1")
    has_ref=bool(parts)
    if not parts:                                            # nothing usable -> empty typed view, app still renders
        con.execute("CREATE VIEW sales AS SELECT CAST('' AS VARCHAR) sku, CAST(0.0 AS DOUBLE) subtotal, "
                    "CAST(0.0 AS DOUBLE) qty, CAST('' AS VARCHAR) marketplaces, CAST(CURRENT_DATE AS DATE) date, "
                    "CAST(NULL AS VARCHAR) reference_code, CAST(NULL AS VARCHAR) store, "
                    "CAST(NULL AS INTEGER) mon, CAST(NULL AS INTEGER) yr WHERE 1=0")
    else:
        con.execute("CREATE VIEW sales_raw AS "+" UNION ALL ".join(parts))
        con.execute("CREATE VIEW sales AS SELECT sku, subtotal, qty, marketplaces, date, reference_code, store, "
                    "EXTRACT(month FROM date) AS mon, EXTRACT(year FROM date) AS yr FROM sales_raw")

    master=load_master()
    cat,num,label=classify(master)
    if master.empty:
        con.execute("CREATE VIEW joined AS SELECT *, FALSE AS _matched FROM sales")
        return con,[],[],[],0.0,has_ref
    keep=["sku_code"]+cat+num+label
    keep=[c for c in keep if c in master.columns]
    m=master[keep].drop_duplicates("sku_code").copy()
    for c in num:
        if c in m.columns: m[c]=pd.to_numeric(m[c],errors="coerce")
    con.register("master_df", m)
    con.execute("CREATE VIEW joined AS "
                "SELECT s.*, m.* EXCLUDE(sku_code), (m.sku_code IS NOT NULL) AS _matched "
                "FROM sales s LEFT JOIN master_df m ON s.sku = m.sku_code")
    mr=con.execute("SELECT AVG(CASE WHEN _matched THEN 1.0 ELSE 0.0 END)*100 FROM joined").fetchone()[0]
    return con,cat,num,label,(mr or 0.0),has_ref

try:
    con,CAT,NUM,LABEL,MATCH,_HAS_REF = build_everything()
    # Promote ONLY the exact columns we want as filters: product_name and Color.
    # Exact (case-insensitive) match only — avoids pulling in "PO Product Name",
    # "OLD COLOUR NAME", "Color Category", etc.
    def _promote_exact(*targets):
        for t in targets:
            for c in list(LABEL):              # only promote from label cols
                if c.lower().strip()==t and c not in CAT:
                    CAT.insert(0, c); return c
        return None
    _promote_exact("product_name","product name")
    _promote_exact("color","colour")
except Exception:
    st.title("Data load error"); st.error("Failed while preparing data:")
    st.code(traceback.format_exc())
    st.info("Check: Drive file shared with service account & is Parquet/CSV; master sheet shared.")
    st.stop()

def Q(sql): return con.execute(sql).df()

# ---------- AI assistant (Gemini text-to-SQL, optional) ----------
# Natural language -> DuckDB SQL over the `joined` view. We send the model only the
# SCHEMA (column names/types) + the question -- never the data rows -- run the SQL
# locally, then (best-effort) ask the model to phrase the answer. Stays dynamic: the
# schema is read live from `joined`, so new master columns are usable with zero code change.
import re
GEMINI_API_KEY = st.secrets.get("GEMINI_API_KEY","")
GEMINI_MODEL   = st.secrets.get("GEMINI_MODEL","gemini-2.0-flash-lite")  # flash-lite = most generous free tier
AI_ROW_CAP     = 5000   # hard cap on rows an AI query may materialise (memory safety)

_SQL_SYS = (
 "You are a senior analytics engineer. Translate the user's question into ONE DuckDB SQL "
 "query over a single view named \"joined\". Return ONLY the SQL -- no prose, no markdown.\n\n"
 "HARD RULES:\n"
 "- Read-only: a single SELECT (optionally a leading WITH ...). Never use "
 "INSERT/UPDATE/DELETE/CREATE/DROP/ALTER/ATTACH/COPY/PRAGMA or any file-reading function.\n"
 "- Query ONLY the view \"joined\". Use ONLY the columns listed below -- never invent columns.\n"
 "- DuckDB dialect.\n"
 "- Use these exact metric definitions so results match the dashboard:\n"
 "    revenue / subtotal = SUM(subtotal)      -- amounts are Indian Rupees (INR)\n"
 "    units              = SUM(qty)\n"
 "    orders             = COUNT(DISTINCT reference_code)   -- distinct invoices\n"
 "- \"marketplaces\" is the sales channel. \"date\" is a DATE; \"mon\"/\"yr\" are its month/year.\n"
 "- Alias every aggregate with a clear, human-readable name.\n"
 "- For 'top N' use ORDER BY <measure> DESC LIMIT N. Keep result sets small.\n"
 "- If the question is ambiguous, choose a sensible interpretation.\n\n"
 "Columns of \"joined\" (name : type):\n{schema_lines}\n\nData spans {DMIN} to {DMAX}."
)
_ANS_SYS = (
 "You are a concise analyst for an Indian D2C activewear brand. Given the user's question and the "
 "query result as CSV, answer in 1-3 sentences of plain English. Show money with the rupee symbol "
 "(₹) and thousands separators; show counts with thousands separators. Do not output SQL or "
 "tables. If the result is empty, say that no data matched."
)

@st.cache_data(ttl=3600)
def ai_schema():
    try:
        return [(r[0],r[1]) for r in con.execute("DESCRIBE joined").fetchall()]
    except Exception:
        return []

def _gemini(prompt, system=None, temperature=0.1, timeout=45, _tries=3):
    """POST to Gemini. Caps output and disables 'thinking' tokens (the big hidden output-token cost on
    flash thinking-models — a simple task can otherwise burn thousands), so each call stays cheap.
    Retries transient (per-minute) 429/503 with backoff, never retries a per-day quota, and surfaces
    a clear, actionable message instead of a raw 429."""
    import requests, time, json as _json
    url=f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"
    gen={"temperature":temperature,"maxOutputTokens":1024,"thinkingConfig":{"thinkingBudget":0}}
    body={"contents":[{"parts":[{"text":prompt}]}],"generationConfig":gen}
    if system: body["systemInstruction"]={"parts":[{"text":system}]}
    for attempt in range(_tries):
        r=requests.post(url,headers={"x-goog-api-key":GEMINI_API_KEY,"Content-Type":"application/json"},
                        json=body,timeout=timeout)
        if r.status_code==200:
            cands=r.json().get("candidates",[])
            if not cands: raise RuntimeError(str(r.json().get("promptFeedback") or "No response from model"))
            return "".join(p.get("text","") for p in cands[0].get("content",{}).get("parts",[])).strip()
        delay,per_day,emsg=None,False,r.text
        try:                                   # dig the exact quota + suggested wait out of the error body
            err=_json.loads(r.text).get("error",{}); emsg=err.get("message",r.text)
            for d in err.get("details",[]):
                if "RetryInfo" in d.get("@type","") and d.get("retryDelay"):
                    try: delay=float(str(d["retryDelay"]).rstrip("s"))
                    except Exception: pass
                if "QuotaFailure" in d.get("@type","") and any("PerDay" in v.get("quotaId","") for v in d.get("violations",[])):
                    per_day=True
        except Exception: pass
        if r.status_code==400 and "thinking" in emsg.lower() and "thinkingConfig" in gen:
            gen.pop("thinkingConfig",None); continue                       # model doesn't accept the flag -> drop & retry
        if r.status_code in (429,503) and not per_day and attempt<_tries-1:
            time.sleep(min(delay or 2*(attempt+1), 12)); continue          # transient -> back off and retry
        if r.status_code==429:
            why=("daily free-tier quota is used up — resets ~midnight US-Pacific" if per_day
                 else "per-minute rate limit hit — wait a moment, ask one question at a time")
            raise RuntimeError(f"quota exceeded (429): {why}. Model '{GEMINI_MODEL}'. Options: switch to "
                               f"gemini-2.0-flash-lite, slow down, or enable billing (new Google Cloud "
                               f"accounts get free credit). [{emsg[:150]}]")
        raise RuntimeError(f"Gemini API {r.status_code}: {emsg[:300]}")
    raise RuntimeError("Gemini API: still rate-limited after retries — wait a minute and ask one question.")

def _extract_sql(text):
    m=re.search(r"```(?:sql)?\s*(.*?)```",text,re.S|re.I)
    return (m.group(1) if m else text).strip().rstrip(";").strip()

@st.cache_data(ttl=3600, show_spinner=False)
def _gen_sql(question, schema_lines):
    # cached: repeating a question (or re-clicking an example chip) costs zero extra Gemini calls
    return _extract_sql(_gemini(question, system=_SQL_SYS.format(schema_lines=schema_lines, DMIN=DMIN, DMAX=DMAX)))

_AI_FORBIDDEN=re.compile(
 r"\b(attach|detach|copy|insert|update|delete|drop|create|alter|pragma|install|load|export|import|"
 r"call|truncate|grant|revoke|vacuum|checkpoint|read_csv|read_csv_auto|read_parquet|read_json|"
 r"read_json_auto|read_text|read_blob|parquet_scan|csv_scan|glob|sniff_csv)\b",re.I)
def _safe_select(sql):
    low=sql.lower().lstrip()
    if not (low.startswith("select") or low.startswith("with")): return False  # SELECT/WITH only
    if ";" in sql.strip().rstrip(";"): return False                            # no stacked statements
    if "joined" not in low: return False                                       # must query our view
    if _AI_FORBIDDEN.search(sql): return False                                 # no DDL/DML/file access
    return True

def _fmt(v):
    try:
        f=float(v); return f"{f:,.0f}" if f==int(f) else f"{f:,.2f}"
    except Exception:
        return v

def _auto_chart(df):
    if df is None or df.empty or df.shape[1]<2 or len(df)>200: return None
    num=[c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    if not num: return None
    y=num[-1]; dims=[c for c in df.columns if c!=y]
    if not dims: return None
    x=dims[0]
    if pd.api.types.is_datetime64_any_dtype(df[x]): return px.line(df,x=x,y=y,markers=True)
    if len(df)<=30: return px.bar(df.sort_values(y,ascending=False),x=x,y=y,text_auto=".2s")
    return None

def _render_result(df):
    if df is None: return
    if getattr(df,"empty",False): st.info("No rows matched that question."); return
    if df.shape==(1,1) and pd.api.types.is_numeric_dtype(df.iloc[:,0]):
        st.metric(str(df.columns[0]),_fmt(df.iloc[0,0])); return
    try:
        num=[c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        st.dataframe(df.style.format({c:_fmt for c in num}) if num else df,width='stretch')
    except Exception:
        st.dataframe(df,width='stretch')
    try:
        fig=_auto_chart(df)
        if fig is not None: plot(fig,width='stretch')
    except Exception:
        pass

# bounds for date picker (cheap min/max query)
try:
    b=Q("SELECT min(date) lo, max(date) hi FROM sales").iloc[0]
    DMIN=pd.to_datetime(b.lo).date(); DMAX=pd.to_datetime(b.hi).date()
except Exception:
    import datetime as _dt; DMIN=_dt.date(2024,1,1); DMAX=_dt.date.today()

# ---------- sidebar ----------
st.sidebar.markdown(
    f'<img src="data:image/png;base64,{LOGO_B64}" style="width:100%;max-width:200px;margin:2px 0 14px;"/>',
    unsafe_allow_html=True)
st.sidebar.title("Controls")
if st.sidebar.button("🧹 Clear all filters"):       # resets every filter (date, channel, store, product); keeps the metric
    for _k in [k for k in st.session_state if k.startswith("f_")]: del st.session_state[_k]
    st.rerun()
metric=st.sidebar.radio("Metric",["subtotal","qty","orders"],horizontal=True,
                        format_func=lambda x:{"subtotal":"Subtotal","qty":"Units","orders":"Orders"}[x])
_mlabels={"subtotal":"Subtotal","qty":"Units","orders":"Orders"}
mlab=_mlabels[metric]
# Orders = distinct invoices (reference_code); others are sums
if metric=="orders":
    agg=("COUNT(DISTINCT reference_code)" if _HAS_REF else "COUNT(*)")
else:
    agg=f"SUM({metric})"
FY_TARGET=st.sidebar.number_input("FY revenue target (₹ Cr)", value=760.0, step=10.0, key="fy_target")*1e7  # for the pacing ring; set your real number
_dc1,_dc2=st.sidebar.columns(2)
start=_dc1.date_input("Start date", value=DMIN, min_value=DMIN, max_value=DMAX, key="f_start")
end  =_dc2.date_input("End date",   value=DMAX, min_value=DMIN, max_value=DMAX, key="f_end")
if start>end: start,end=end,start   # guard against reversed selection

def distinct(col):
    try:
        return [str(r[0]) for r in con.execute(f'SELECT DISTINCT "{col}" FROM joined WHERE "{col}" IS NOT NULL ORDER BY 1').fetchall() if str(r[0])!=""]
    except Exception:
        return []

selected={}
_all_ch=distinct("marketplaces")
_default_ch=[c for c in _all_ch if c.lower().strip() not in ("internal",)]  # Retail is a first-class channel now -> on by default
ch=st.sidebar.multiselect("Channel", _all_ch, default=_default_ch, key="f_ch")
# If user clears all, treat as "all selected" so the dashboard isn't empty
if ch: selected["marketplaces"]=ch
elif _all_ch and not ch: selected["marketplaces"]=_default_ch
# Store filter — only the retail source populates `store`; appears when retail data is present
_stores=distinct("store")
if _stores:
    sv=st.sidebar.multiselect("Store (retail)", _stores, key="f_store")
    if sv: selected["store"]=sv
if CAT:
    st.sidebar.markdown("**Product filters**")
    for c in CAT[:6]:
        v=st.sidebar.multiselect(c, distinct(c), key=f"f_cat_{c}")
        if v: selected[c]=v
    if CAT[6:] or NUM:
        with st.sidebar.expander("More filters"):
            for c in CAT[6:]:
                v=st.multiselect(c, distinct(c), key=f"f_cat_{c}")
                if v: selected[c]=v
            for c in NUM:
                try:
                    r=con.execute(f'SELECT min("{c}") lo, max("{c}") hi FROM joined').fetchone()
                    if r and r[0] is not None and r[1] is not None and r[0]<r[1]:
                        rng=st.slider(c, float(r[0]), float(r[1]), (float(r[0]),float(r[1])), key=f"f_num_{c}")
                        selected["__num__"+c]=rng
                except Exception: pass

def sin(col,vals): return "\""+col+"\" IN ("+",".join("'"+v.replace("'","''")+"'" for v in vals)+")"
def build_where(d0,d1):                              # same filters, any date range (needed for deltas)
    parts=[f"date BETWEEN '{d0}' AND '{d1}'"]
    for col,vals in selected.items():
        if col.startswith("__num__"):
            c=col[7:]; parts.append(f'"{c}" BETWEEN {vals[0]} AND {vals[1]}')
        else:
            parts.append(sin(col,vals))
    return " AND ".join(parts)
WHERE=build_where(start,end)                         # selected window (unchanged behaviour)
import datetime as _dt
_span=(end-start); _prev_end=start-_dt.timedelta(days=1); _prev_start=_prev_end-_span
PREV_WHERE=build_where(_prev_start,_prev_end)        # immediately-preceding equal window, for deltas

# ---------- overview helpers (hero KPIs, live insight, growth drivers, ghosted trend) ----------
def _delta_html(cur,prev):
    try: cur=float(cur); prev=float(prev)
    except Exception: return ""
    if prev==0 or cur!=cur or prev!=prev: return ""      # guard None / NaN / zero (no prior window)
    pct=(cur-prev)/prev*100.0
    cls="bc-up" if pct>=0 else "bc-down"; arrow="▲" if pct>=0 else "▼"
    return (f'<span class="{cls}"><span style="font-size:8px">{arrow}</span>{abs(pct):.1f}%'
            f'<span style="font-weight:500;font-size:11px;color:#7c8aa0">vs prev</span></span>')

def render_kpis():
    txn="COUNT(DISTINCT reference_code)" if _HAS_REF else "COUNT(*)"
    q=f"SELECT SUM(subtotal) rev, SUM(qty) units, {txn} orders, COUNT(DISTINCT sku) skus FROM joined WHERE "
    cur,prev=Q(q+WHERE).iloc[0], Q(q+PREV_WHERE).iloc[0]
    rev,units,orders,skus=(cur.rev or 0),(cur.units or 0),(cur.orders or 0),(cur.skus or 0)
    aov=(rev/orders) if orders else 0
    paov=((prev.rev or 0)/prev.orders) if (prev.orders or 0) else 0
    frac=min(max(rev/FY_TARGET,0),1) if FY_TARGET else 0; off=327*(1-frac)
    ring=(f'<div class="bc-ring"><div class="wrap"><svg width="118" height="118" viewBox="0 0 118 118">'
          f'<circle cx="59" cy="59" r="52" fill="none" stroke="#eef0f6" stroke-width="12"/>'
          f'<circle class="fg" cx="59" cy="59" r="52" fill="none" stroke="#6366f1" stroke-width="12" stroke-linecap="round" '
          f'stroke-dasharray="327" stroke-dashoffset="{off:.1f}" transform="rotate(-90 59 59)"/></svg>'
          f'<div class="ctr"><span style="font:800 22px Inter;color:#0f1115;letter-spacing:-.5px">{frac*100:.0f}%</span>'
          f'<span style="font:600 9px Inter;letter-spacing:.5px;text-transform:uppercase;color:#9aa0ad">to target</span></div></div>'
          f'<span style="font:500 11px Inter;color:#9aa0ad">FY target <b style="color:#5a6070">{inr_cr(FY_TARGET)}</b></span></div>')
    st.markdown(f'''<div class="bc-hero">
      <div class="lead"><span class="bc-lab">Total Subtotal</span>
        <div style="display:flex;align-items:flex-end;gap:13px"><span class="bc-big">{inr_cr(rev)}</span>{_delta_html(rev,prev.rev)}</div>
        <span class="bc-sub">₹{ind_group(rev)} · {ind_group(skus)} active SKUs · {inr_abbr(orders)} orders</span></div>
      <div class="rule"></div>{ring}
      <div class="trio">
        <div class="stat"><span class="bc-lab">Units</span><span class="bc-mid">{inr_abbr(units)}</span>{_delta_html(units,prev.units)}</div>
        <div class="stat"><span class="bc-lab">Orders</span><span class="bc-mid">{inr_abbr(orders)}</span>{_delta_html(orders,prev.orders)}</div>
        <div class="stat"><span class="bc-lab">Avg order value</span><span class="bc-mid">₹{ind_group(aov)}</span>{_delta_html(aov,paov)}</div>
      </div></div>''', unsafe_allow_html=True)

def build_insight():
    txn="COUNT(DISTINCT reference_code)" if _HAS_REF else "COUNT(*)"
    cur=Q(f"SELECT SUM(subtotal) rev,{txn} orders FROM joined WHERE {WHERE}").iloc[0]
    prv=Q(f"SELECT SUM(subtotal) rev FROM joined WHERE {PREV_WHERE}").iloc[0]
    rev,prev_rev=float(cur.rev or 0),float(prv.rev or 0)
    pct=(rev-prev_rev)/prev_rev*100 if prev_rev>0 else 0     # >0 also rejects NaN
    qc="SELECT marketplaces ch, SUM(subtotal) v FROM joined WHERE {w} GROUP BY 1"
    c1=Q(qc.format(w=WHERE)).set_index("ch")["v"].astype(float)
    c0=Q(qc.format(w=PREV_WHERE)).set_index("ch")["v"].astype(float)
    contrib={c: float(c1.get(c,0))-float(c0.get(c,0)) for c in set(c1.index)|set(c0.index)}
    aov=rev/float(cur.orders) if cur.orders else 0
    arrow,col=("▲","#0f9d6b") if pct>=0 else ("▼","#c2453b")
    parts=[f'Revenue reached <b>{inr_cr(rev)}</b>, <b style="color:{col}">{arrow} {abs(pct):.1f}%</b> vs the prior period.']
    if contrib:
        top=max(contrib,key=contrib.get)
        if contrib[top]>0: parts.append(f'<b>{top}</b> contributed the most (+{inr_abbr(abs(contrib[top]))}).')
    parts.append(f'AOV is <b>₹{ind_group(aov)}</b>.')
    st.markdown(f'<div class="bc-insight"><span class="ic">✦</span><div>{" ".join(parts)}</div></div>', unsafe_allow_html=True)

def growth_waterfall():
    qc="SELECT marketplaces ch, SUM(subtotal) v FROM joined WHERE {w} GROUP BY 1"
    c1=Q(qc.format(w=WHERE)).set_index("ch")["v"].astype(float)
    c0=Q(qc.format(w=PREV_WHERE)).set_index("ch")["v"].astype(float)
    if c0.empty: st.info("Not enough history for a driver breakdown."); return
    chans=sorted(set(c1.index)|set(c0.index))
    deltas=sorted([(c, float(c1.get(c,0))-float(c0.get(c,0))) for c in chans], key=lambda t:t[1], reverse=True)
    base,total=float(c0.sum()),float(c1.sum())
    xs=["Prior"]+[c for c,_ in deltas]+["Now"]; ys=[base]+[d for _,d in deltas]+[0]
    meas=["absolute"]+["relative"]*len(deltas)+["total"]
    txt=[inr_abbr(base)]+[("+" if d>=0 else "−")+inr_abbr(abs(d)) for _,d in deltas]+[inr_abbr(total)]
    fig=go.Figure(go.Waterfall(orientation="v", measure=meas, x=xs, y=ys, text=txt, textposition="outside",
        connector={"line":{"color":"rgba(16,17,21,.16)","width":1}},
        increasing={"marker":{"color":"#6366f1"}}, decreasing={"marker":{"color":"#f43f5e"}}, totals={"marker":{"color":"#0f1115"}},
        hovertemplate="%{x}<br>%{y:+,.0f}<extra></extra>"))
    fig.update_layout(height=320, title=f"What drove the change · {mlab}", showlegend=False)
    fig.update_xaxes(showgrid=False); fig.update_yaxes(range=[min(base,total)*0.96, max(base,total)*1.05])
    plot(fig, width="stretch")

def trend_with_ghost():
    g=st.radio("Granularity",["Daily","Weekly","Monthly"],horizontal=True,index=2,key="g")
    tr={"Daily":"day","Weekly":"week","Monthly":"month"}[g]
    cur=Q(f"SELECT date_trunc('{tr}',date) period,{agg} v FROM joined WHERE {WHERE} GROUP BY 1 ORDER BY 1")
    prv=Q(f"SELECT date_trunc('{tr}',date) period,{agg} v FROM joined WHERE {PREV_WHERE} GROUP BY 1 ORDER BY 1")
    fig=go.Figure()
    if not prv.empty:
        fig.add_trace(go.Scatter(x=cur["period"], y=prv["v"].reindex(range(len(cur))).values, mode="lines",
            name="Prior period", line=dict(color="rgba(90,96,112,.40)", width=1.6, dash="dot")))
    fig.add_trace(go.Scatter(x=cur["period"], y=cur["v"], mode="lines", name=mlab,
        line=dict(color="#6366f1", width=2.8, shape="spline"), fill="tozeroy", fillcolor="rgba(99,102,241,0.12)"))
    if len(cur):
        fig.add_annotation(x=cur["period"].iloc[-1], y=cur["v"].iloc[-1], text=inr_abbr(cur["v"].iloc[-1]),
            showarrow=False, xanchor="left", xshift=8, font=dict(family="Inter", size=12, color="#6366f1"))
    fig.update_layout(height=320, title=f"{g} {mlab}", showlegend=True, yaxis_title=None, xaxis_title=None)
    plot(fig, width="stretch")

# ---------- header (title left, logo right) ----------
hL, hR = st.columns([2,1], vertical_alignment="center")
with hL:
    st.title("D2C Sales Dashboard")
    active=[f"{k}: {', '.join(v)}" for k,v in selected.items() if not k.startswith('__num__')]
    st.caption(f"{mlab} · {start} → {end}"+(" · "+" · ".join(active) if active else ""))
with hR:
    st.markdown(
        f'<div style="text-align:right;"><img src="data:image/png;base64,{LOGO_B64}" style="height:56px;max-width:100%;"/></div>',
        unsafe_allow_html=True)
if not CAT:
    merr=st.session_state.get("_master_error","")
    if merr: st.info(f"Master sheet not loaded ({'permission — share the sheet with the service account' if 'ermission' in merr or '403' in merr else merr}). Showing sales-only views.")
    else: st.info("No master attributes — connect the master sheet to unlock product filters.")
elif MATCH<99:
    st.warning(f"SKU match rate: {MATCH:.1f}%. Unmatched rows count in totals but carry no attributes.")

st.divider()

tabs=["Trend","Channel"]+(["By Attribute"] if CAT else [])+["Compare","SKUs","Pivot","Ask AI"]
T=dict(zip(tabs, st.tabs(tabs)))

with T["Trend"]:
    build_insight()                                          # plain-English takeaway
    render_kpis()                                            # hero number + target ring + trio (with deltas)
    st.write("")
    cw,ct=st.columns([1.25,1])
    with cw: growth_waterfall()                              # the "why" (per-channel YoY contribution)
    with ct: trend_with_ghost()                              # trend + prior-period ghost
    cda,cdb=st.columns([1.05,1])
    with cda:                                                # revenue by channel
        sh=Q(f"SELECT marketplaces,{agg} v FROM joined WHERE {WHERE} GROUP BY 1 ORDER BY 2 DESC")
        d=px.pie(sh,names="marketplaces",values="v",hole=0.66,title="Revenue by Channel",color="marketplaces",color_discrete_map=CHANNEL_COLORS)
        d.update_traces(textinfo="none", marker=dict(line=dict(color="#fff",width=2.5)))
        d.add_annotation(text=inr_abbr(sh["v"].sum()), x=0.5, y=0.5, xref="paper", yref="paper", showarrow=False, font=dict(size=18,color="#0f1115"))
        d.update_layout(height=300, showlegend=True); plot(d,width="stretch")
    with cdb:                                                # top colours, each bar in its actual colour
        ccol=_pick_colour_col()
        if ccol:
            cc=Q(f'SELECT "{ccol}" k,{agg} v FROM joined WHERE {WHERE} AND "{ccol}" IS NOT NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 6')
            bar=px.bar(cc,x="v",y="k",orientation="h",title="Top Colours",color="k",color_discrete_map={n:colour_to_hex(n) for n in cc["k"]})
            bar.update_traces(text=[inr_abbr(v) for v in cc["v"]],textposition="outside",cliponaxis=False,showlegend=False)
            bar.update_layout(height=300, yaxis=dict(categoryorder="total ascending",automargin=True,title=None), xaxis=dict(visible=False, range=[0,(cc["v"].max() or 1)*1.18]))
            plot(bar,width="stretch")
        else: st.caption("Connect the master sheet to see the colour breakdown.")
    # Price vs volume (kept): Units (bars) + Subtotal/unit ASP (line, right axis)
    _g=st.session_state.get("g","Monthly"); _tr={"Daily":"day","Weekly":"week","Monthly":"month"}[_g]
    pv=Q(f"SELECT date_trunc('{_tr}',date) period, SUM(qty) units, SUM(subtotal) rev FROM joined WHERE {WHERE} GROUP BY 1 ORDER BY 1")
    pv["asp"]=(pv["rev"]/pv["units"].replace(0,pd.NA)).fillna(0); _few=len(pv)<=40
    pf=go.Figure()
    pf.add_bar(x=pv["period"],y=pv["units"],name="Units",marker_color="#c7c4f5",
               text=(pv["units"].map(inr_abbr) if _few else None),texttemplate="%{text}",textposition="outside")
    pf.add_trace(go.Scatter(x=pv["period"],y=pv["asp"],name="Subtotal / unit (₹)",yaxis="y2",
               mode=("lines+markers+text" if _few else "lines+markers"),line=dict(color="#6366f1"),
               text=(pv["asp"].map(inr_abbr) if _few else None),texttemplate="%{text}",textposition="top center"))
    pf.update_layout(height=360,title="Units vs Subtotal / unit  (price- or volume-led?)",
               yaxis=dict(title="Units"),yaxis2=dict(title="₹ / unit",overlaying="y",side="right"))
    plot(pf,width='stretch')

with T["Channel"]:
    gc=st.radio("Granularity",["Daily","Weekly","Monthly"],horizontal=True,index=2,key="gchan")
    trc={"Daily":"day","Weekly":"week","Monthly":"month"}[gc]
    df=Q(f"SELECT date_trunc('{trc}',date) period,marketplaces,{agg} v FROM joined WHERE {WHERE} GROUP BY 1,2 ORDER BY 1")
    line=px.line(df,x="period",y="v",color="marketplaces",title=f"{gc} {mlab} by Channel",color_discrete_map=CHANNEL_COLORS)
    line.update_traces(mode="lines")                         # no markers/labels — direct end-labels instead
    for _,r in df.sort_values("period").groupby("marketplaces").tail(1).iterrows():
        line.add_annotation(x=r["period"],y=r["v"],text=r["marketplaces"],showarrow=False,xanchor="left",xshift=8,
            font=dict(family="Inter",size=11,color=CHANNEL_COLORS.get(r["marketplaces"],"#5a6070")))
    line.update_layout(height=380,showlegend=False,margin=dict(r=120))
    plot(line,width="stretch")
    sh=Q(f"SELECT marketplaces,{agg} v FROM joined WHERE {WHERE} GROUP BY 1 ORDER BY 2 DESC")
    a,b=st.columns(2)
    with a:
        d=px.pie(sh,names="marketplaces",values="v",hole=0.55,title="Channel Share",color="marketplaces",color_discrete_map=CHANNEL_COLORS)
        d.update_traces(textinfo="percent",marker=dict(line=dict(color="#fff",width=2))); d.update_layout(height=320); plot(d,width="stretch")
    with b:
        bar=px.bar(sh,x="marketplaces",y="v",title="Channel Totals",color="marketplaces",color_discrete_map=CHANNEL_COLORS)
        bar.update_traces(text=[inr_abbr(v) for v in sh["v"]],textposition="outside",showlegend=False)
        bar.update_layout(height=320,yaxis=dict(visible=False),xaxis_title=None); plot(bar,width="stretch")

if CAT:
    with T["By Attribute"]:
        dim=st.selectbox("Break down by",CAT)
        df=Q(f'SELECT "{dim}" k,{agg} v FROM joined WHERE {WHERE} AND "{dim}" IS NOT NULL GROUP BY 1 ORDER BY 2 DESC')
        is_colour=dim.lower().strip() in ("color","colour")
        cmap={n:colour_to_hex(n) for n in df["k"]} if is_colour else None
        bar=px.bar(df,x="v",y="k",orientation="h",title=f"{mlab} by {dim}",color="k" if is_colour else None,color_discrete_map=cmap)
        bar.update_traces(text=[inr_abbr(v) for v in df["v"]],textposition="outside",cliponaxis=False,showlegend=False)
        bar.update_layout(height=max(400,len(df)*28),yaxis=dict(categoryorder="total ascending",automargin=True,title=None),
                          xaxis=dict(visible=False,range=[0,(df["v"].max() or 1)*1.15]))   # automargin keeps long colour names visible
        plot(bar,width="stretch")
        trd=Q(f'SELECT date_trunc(\'month\',date) period,"{dim}" k,{agg} v FROM joined WHERE {WHERE} AND "{dim}" IS NOT NULL GROUP BY 1,2 ORDER BY 1')
        ln=px.line(trd,x="period",y="v",color="k",title=f"Monthly {mlab} by {dim}"); ln.update_traces(mode="lines"); ln.update_layout(height=420)
        plot(ln,width="stretch")

with T["Compare"]:
    mode=st.selectbox("Comparison",["Year over Year","Month over Month"])
    if mode=="Year over Year":
        df=Q(f'SELECT mon "month",yr "year",{agg} v FROM joined WHERE {WHERE} GROUP BY 1,2 ORDER BY 1,2')
        df["year"]=df["year"].astype(int); years=sorted(df["year"].unique())
        greys=["#d4d7e0","#b3b8c6","#9aa1b0","#6b7280","#2c3142"]
        cmap={str(y):greys[min(i,len(greys)-1)] for i,y in enumerate(years)}
        if years: cmap[str(years[-1])]="#6366f1"            # latest year = accent, older greyscaled
        df["year"]=df["year"].astype(str)
        fig=px.line(df,x="month",y="v",color="year",title=f"YoY {mlab}",color_discrete_map=cmap); fig.update_traces(mode="lines")
        for y in years:
            sub=df[df["year"]==str(y)].sort_values("month")
            if len(sub): fig.add_annotation(x=sub["month"].iloc[-1],y=sub["v"].iloc[-1],text=str(y),showarrow=False,xanchor="left",xshift=8,font=dict(family="Inter",size=11.5,color=cmap[str(y)]))
        fig.update_layout(height=420,showlegend=False,margin=dict(r=54),xaxis_title="Month")
        plot(fig,width="stretch")
    else:
        df=Q(f"SELECT date_trunc('month',date) period,{agg} v FROM joined WHERE {WHERE} GROUP BY 1 ORDER BY 1"); df["MoM %"]=(df["v"].pct_change()*100).round(1)
        fig=go.Figure(); fig.add_bar(x=df["period"],y=df["v"],name=mlab,marker_color="#6366f1")
        fig.add_trace(go.Scatter(x=df["period"],y=df["MoM %"],name="MoM %",yaxis="y2",mode="lines+markers",line=dict(color="#f43f5e")))
        fig.update_layout(height=440,yaxis=dict(title=mlab),yaxis2=dict(title="MoM %",overlaying="y",side="right"))
        plot(fig,width='stretch')

with T["SKUs"]:
    n=st.slider("Top N SKUs",5,50,15)
    _attr=CAT+LABEL                                          # describe each SKU with product name + colour + size
    def _pickcol(*subs):
        for c in _attr:                                      # exact match first...
            if c.lower().strip() in subs: return c
        for c in _attr:                                      # ...then contains
            if any(s in c.lower() for s in subs): return c
        return None
    desc=[c for c in [_pickcol("product_name","product name","name"),_pickcol("color","colour"),_pickcol("size")] if c]
    sel=", ".join(["sku"]+[f'"{c}"' for c in desc])
    ord_expr=("COUNT(DISTINCT reference_code)" if _HAS_REF else "COUNT(*)")
    _orderby={"subtotal":"rev","qty":"units","orders":"orders"}[metric]
    df=Q(f'SELECT {sel}, SUM(subtotal) rev, SUM(qty) units, {ord_expr} orders FROM joined WHERE {WHERE} GROUP BY {sel} ORDER BY {_orderby} DESC LIMIT {n}')
    _mv=float(df["rev"].max()) if len(df) else 1.0       # empty filter → NaN guard for the progress bar
    if _mv!=_mv or _mv<=0: _mv=1.0
    cfg={"rev":st.column_config.ProgressColumn("Revenue (₹)",format="₹%d",min_value=0,max_value=_mv),
         "units":st.column_config.NumberColumn("Units",format="%d"),
         "orders":st.column_config.NumberColumn("Orders",format="%d")}
    st.dataframe(df,width="stretch",hide_index=True,column_config=cfg)

with T["Pivot"]:
    # Columns dropdown: time options + only LOW-cardinality dims (so we never try to
    # render thousands of columns, which breaks the table). High-cardinality fields
    # like product_name / Color are fine for ROWS but not for COLUMNS.
    def _card(col):
        try: return con.execute(f'SELECT COUNT(DISTINCT "{col}") FROM joined').fetchone()[0]
        except Exception: return 9999
    dim_opts=(CAT if CAT else [])+["marketplaces"]
    low_card_dims=[c for c in dim_opts if _card(c)<=30]
    col_opts=["Month (YYYY-MM)","Week (start)","Day (YYYY-MM-DD)","Quarter","Year"]+low_card_dims
    cpa,cpb=st.columns(2)
    rd=cpa.selectbox("Rows",dim_opts,key="piv_rows")
    cd=cpb.selectbox("Columns",col_opts,key="piv_cols")
    if cd=="Month (YYYY-MM)":
        col_sql="yr||'-'||lpad(mon::VARCHAR,2,'0')"; order_sql="2"
    elif cd=="Week (start)":
        col_sql="strftime(date_trunc('week',date),'%Y-%m-%d')"; order_sql="2"
    elif cd=="Day (YYYY-MM-DD)":
        col_sql="strftime(date,'%Y-%m-%d')"; order_sql="2"
    elif cd=="Year":
        col_sql="CAST(yr AS VARCHAR)"; order_sql="2"
    elif cd=="Quarter":
        col_sql="yr||'-Q'||CAST(CEIL(mon/3.0) AS INT)"; order_sql="2"
    else:
        col_sql=f'"{cd}"'; order_sql="1"
    extra_where=f' AND {col_sql} IS NOT NULL' if cd in low_card_dims else ''
    df=Q(f'SELECT "{rd}" r, {col_sql} c, {agg} v FROM joined WHERE {WHERE} AND "{rd}" IS NOT NULL{extra_where} GROUP BY 1,2 ORDER BY {order_sql}')
    if df.empty:
        st.info("No data for this selection.")
    elif df["c"].nunique()>80:
        # guard: Day/Week over a long range would build a huge table (and OOM the host) -> ask for a coarser column
        st.warning(f"'{cd}' would make {df['c'].nunique():,} columns over this date range — too wide to render. "
                   "Pick a coarser column (Month / Quarter / Year) or narrow the date range.")
    else:
        piv=df.pivot(index="r",columns="c",values="v").fillna(0)
        piv["Total"]=piv.sum(axis=1)
        piv=piv.sort_values("Total",ascending=False)
        vmax=float(piv.drop(columns="Total").values.max() or 1)
        def _heat(col):                                      # value-shaded cells (no matplotlib) — darker = higher
            out=[]
            for v in col:
                if col.name=="Total":
                    out.append("font-weight:700;color:#0f1115;background:#f3f4fb")
                else:
                    a=0 if vmax<=0 else max(0.0,min(0.55,float(v)/vmax))
                    out.append(f"background-color:rgba(99,102,241,{a:.3f});color:{'#fff' if a>=0.42 else '#0f1115'}")
            return out
        st.caption(f"{len(piv):,} rows · {len(piv.columns)-1} columns · darker = higher")
        st.dataframe(piv.style.format(ind_group).apply(_heat,axis=0),width='stretch',height=480)
        st.download_button("Download CSV",piv.to_csv().encode(),"pivot.csv","text/csv")

with T["Ask AI"]:
    st.subheader("Ask AI")
    if not GEMINI_API_KEY:
        st.info(
            "**Assistant is off.** Add a Gemini API key to switch it on. In `.streamlit/secrets.toml`:\n\n"
            "```toml\nGEMINI_API_KEY = \"your-key-here\"\n"
            "# optional, defaults to gemini-2.0-flash-lite\nGEMINI_MODEL = \"gemini-2.0-flash-lite\"\n```\n\n"
            "The key is read from `st.secrets` (gitignored) — never paste it into the code. Rerun after saving.")
    else:
        st.caption("Ask in plain English — questions are translated to SQL and run on your live data. "
                   "Aggregates use the dashboard's definitions (Subtotal · Units · Orders). "
                   "Note: the sidebar filters are not applied here — mention the period/segment in your question.")
        if "ai_msgs" not in st.session_state: st.session_state["ai_msgs"]=[]

        for turn in st.session_state["ai_msgs"]:
            with st.chat_message("user"): st.markdown(turn["q"])
            with st.chat_message("assistant"):
                if turn.get("error"): st.error(turn["error"])
                else:
                    if turn.get("answer"): st.markdown(turn["answer"])
                    _render_result(turn.get("df"))
                if turn.get("sql"):
                    with st.expander("Show SQL"): st.code(turn["sql"],language="sql")

        pending=None
        examples=["Top 10 SKUs by revenue","Monthly revenue trend in 2025",
                  "Revenue share by channel","Total units sold"]
        ecols=st.columns(len(examples))
        for i,e in enumerate(examples):
            if ecols[i].button(e,key=f"ai_ex_{i}"): pending=e
        explain=st.checkbox("Also write a one-line answer (uses a 2nd request)",value=True,
                            help="Turn off to spend only one Gemini request per question — useful on the free tier.")
        with st.form("ai_form",clear_on_submit=True):
            qin=st.text_input("Your question",placeholder="e.g. Which colour sold the most units last month?")
            if st.form_submit_button("Ask") and qin.strip(): pending=qin.strip()

        if pending:
            turn={"q":pending}
            with st.spinner("Thinking…"):
                try:
                    sl="\n".join(f"  {n} : {t}" for n,t in ai_schema())
                    sql=_gen_sql(pending, sl)                       # cached + retries transient throttling
                    turn["sql"]=sql
                    if not _safe_select(sql):
                        turn["error"]="That request didn't produce a safe read-only SELECT. Try rephrasing."
                    else:
                        turn["df"]=Q(f"SELECT * FROM ({sql}) AS _ai LIMIT {AI_ROW_CAP}")
                        if explain:                                 # optional 2nd call — skip to save quota
                            try:
                                turn["answer"]=_gemini(
                                    f"Question: {pending}\n\nResult (CSV):\n{turn['df'].head(50).to_csv(index=False)}",
                                    system=_ANS_SYS)
                            except Exception:
                                turn["answer"]=None
                except Exception as e:
                    turn["error"]=f"AI request failed: {e}"
            st.session_state["ai_msgs"].append(turn)
            st.rerun()
